// src/app/(app)/typewriter/sources.ts

export interface SourceDefinition {
  id: string;
  name: string;
  url: string;
  character: string;           // What makes this source distinctive
  primaryGenres: string[];     // Which umbrella genres this source covers best
  type: 'essay' | 'article' | 'both';
  fetchable: boolean;          // Can be scraped via proxy (true) or seed-only (false)
  fetchUrl?: string;           // URL to scrape if fetchable
  paywalled: boolean;          // Partial or full paywall
}

export const ALL_SOURCES: SourceDefinition[] = [

  // ── LIVE FETCHABLE SOURCES (scraped via /api/typewriter proxy) ──

  {
    id: 'tetw',
    name: 'The Electric Typewriter',
    url: 'https://tetw.org',
    fetchUrl: 'https://tetw.org',
    character: 'The internet\'s finest curated collection of longform essays and articles. No algorithm. No ads. Purely editorial.',
    primaryGenres: ['Life & Personal Experience', 'Arts, Culture & Language', 'Special Collections', 'Society, Politics & History'],
    type: 'both',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'aeon',
    name: 'Aeon',
    url: 'https://aeon.co',
    fetchUrl: 'https://aeon.co/essays',
    character: 'Philosophy, psychology, science — ideas that challenge assumptions. Long, rigorous, deeply human.',
    primaryGenres: ['Psychology & Behavior', 'Science & Technology', 'Life & Personal Experience', 'Arts, Culture & Language'],
    type: 'essay',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'psyche',
    name: 'Psyche',
    url: 'https://psyche.co',
    fetchUrl: 'https://psyche.co/ideas',
    character: 'Aeon\'s sister publication. Practical psychology and the examined life.',
    primaryGenres: ['Psychology & Behavior', 'Life & Personal Experience', 'Health & Medicine'],
    type: 'both',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'nautilus',
    name: 'Nautilus',
    url: 'https://nautil.us',
    fetchUrl: 'https://nautil.us/latest/',
    character: 'Science through the lens of humanity. Physics, biology, neuroscience made beautiful.',
    primaryGenres: ['Science & Technology', 'Environment & Nature', 'Health & Medicine'],
    type: 'both',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'longreads',
    name: 'Longreads',
    url: 'https://longreads.com',
    fetchUrl: 'https://longreads.com/category/essays/',
    character: 'Curated longform from across the web. Personal essays, narrative journalism, memoir.',
    primaryGenres: ['Life & Personal Experience', 'Family & Relationships', 'Travel & Places'],
    type: 'both',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'guardian',
    name: 'The Guardian Long Reads',
    url: 'https://theguardian.com',
    fetchUrl: 'https://www.theguardian.com/news/series/the-long-read',
    character: 'British investigative and narrative journalism. Society, environment, global affairs.',
    primaryGenres: ['Society, Politics & History', 'Environment & Nature', 'Travel & Places'],
    type: 'article',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'jstor',
    name: 'JSTOR Daily',
    url: 'https://daily.jstor.org',
    fetchUrl: 'https://daily.jstor.org/category/arts-humanities/',
    character: 'Academic research made readable. History, science, culture explained with rigor.',
    primaryGenres: ['Society, Politics & History', 'Science & Technology', 'Arts, Culture & Language'],
    type: 'article',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'works_in_progress',
    name: 'Works in Progress',
    url: 'https://worksinprogress.co',
    fetchUrl: 'https://worksinprogress.co/archive/',
    character: 'Progress studies, innovation, economics, social change. Optimistic, rigorous.',
    primaryGenres: ['Science & Technology', 'Society, Politics & History', 'Environment & Nature'],
    type: 'article',
    fetchable: true,
    paywalled: false,
  },
  {
    id: 'caravan',
    name: 'The Caravan',
    url: 'https://caravanmagazine.in',
    fetchUrl: 'https://caravanmagazine.in/essays',
    character: 'India\'s finest longform magazine. Politics, culture, society — deeply reported.',
    primaryGenres: ['Society, Politics & History', 'Arts, Culture & Language', 'Travel & Places'],
    type: 'both',
    fetchable: true,
    paywalled: false,
  },

  // ── SEED-ONLY SOURCES (paywalled or scraping-resistant — in data.ts) ──

  {
    id: 'atlantic',
    name: 'The Atlantic',
    url: 'https://theatlantic.com',
    character: 'American intellectual journalism. Culture, politics, science, ideas at their best.',
    primaryGenres: ['Society, Politics & History', 'Life & Personal Experience', 'Science & Technology', 'Psychology & Behavior'],
    type: 'both',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'new_yorker',
    name: 'The New Yorker',
    url: 'https://newyorker.com',
    character: 'The gold standard of American magazine writing. Profiles, criticism, reportage.',
    primaryGenres: ['Arts, Culture & Language', 'Society, Politics & History', 'Life & Personal Experience'],
    type: 'both',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'harpers',
    name: "Harper's Magazine",
    url: 'https://harpers.org',
    character: 'America\'s oldest magazine. Sharp, political, literary — often contrarian.',
    primaryGenres: ['Society, Politics & History', 'Arts, Culture & Language', 'Life & Personal Experience'],
    type: 'essay',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'lrb',
    name: 'London Review of Books',
    url: 'https://lrb.co.uk',
    character: 'Britain\'s leading intellectual review. Long, serious, essential.',
    primaryGenres: ['Arts, Culture & Language', 'Society, Politics & History', 'Special Collections'],
    type: 'essay',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'nyrb',
    name: 'New York Review of Books',
    url: 'https://nybooks.com',
    character: 'America\'s premier intellectual journal. Critical essays of depth and breadth.',
    primaryGenres: ['Arts, Culture & Language', 'Society, Politics & History', 'Special Collections'],
    type: 'essay',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'foreign_affairs',
    name: 'Foreign Affairs',
    url: 'https://foreignaffairs.com',
    character: 'The definitive journal of international relations, geopolitics, and global economics.',
    primaryGenres: ['Society, Politics & History'],
    type: 'article',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'foreign_policy',
    name: 'Foreign Policy',
    url: 'https://foreignpolicy.com',
    character: 'Global news and analysis. Geopolitics, security, international economics.',
    primaryGenres: ['Society, Politics & History', 'Travel & Places'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'smithsonian',
    name: 'Smithsonian Magazine',
    url: 'https://smithsonianmag.com',
    character: 'History, science, culture, arts — accessible, accurate, wide-ranging.',
    primaryGenres: ['Science & Technology', 'Society, Politics & History', 'Arts, Culture & Language', 'Environment & Nature'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'wired',
    name: 'Wired',
    url: 'https://wired.com',
    character: 'Technology, science, culture — how the digital world shapes human life.',
    primaryGenres: ['Science & Technology'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'vox',
    name: 'Vox',
    url: 'https://vox.com',
    character: 'Explanatory journalism. Complex issues made clear without being simplified.',
    primaryGenres: ['Society, Politics & History', 'Science & Technology', 'Health & Medicine'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'quanta',
    name: 'Quanta Magazine',
    url: 'https://quantamagazine.org',
    character: 'Mathematics and physical science journalism. Rigorous, beautiful, free.',
    primaryGenres: ['Science & Technology'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'the_wire',
    name: 'The Wire',
    url: 'https://thewire.in',
    character: 'Independent Indian journalism. Science, politics, society.',
    primaryGenres: ['Society, Politics & History', 'Science & Technology'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg Businessweek',
    url: 'https://bloomberg.com/businessweek',
    character: 'Business, economics, technology — longform at scale.',
    primaryGenres: ['Science & Technology', 'Society, Politics & History'],
    type: 'article',
    fetchable: false,
    paywalled: true,
  },
  {
    id: 'orion',
    name: 'Orion Magazine',
    url: 'https://orionmagazine.org',
    character: 'Nature, environment, culture. Literary environmental journalism at its finest.',
    primaryGenres: ['Environment & Nature', 'Life & Personal Experience'],
    type: 'essay',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'lapham',
    name: "Lapham's Quarterly",
    url: 'https://laphamsquarterly.org',
    character: 'History through primary sources and contemporary essays. Thematic, rich.',
    primaryGenres: ['Society, Politics & History', 'Arts, Culture & Language'],
    type: 'essay',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'new_statesman',
    name: 'New Statesman',
    url: 'https://newstatesman.com',
    character: 'British centre-left political and cultural commentary.',
    primaryGenres: ['Society, Politics & History', 'Arts, Culture & Language'],
    type: 'article',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'prospect',
    name: 'Prospect Magazine',
    url: 'https://prospectmagazine.co.uk',
    character: 'British intellectual magazine. Ideas, politics, culture, science.',
    primaryGenres: ['Society, Politics & History', 'Arts, Culture & Language', 'Science & Technology'],
    type: 'both',
    fetchable: false,
    paywalled: false,
  },
  {
    id: 'public_domain',
    name: 'Classic Essays (Public Domain)',
    url: 'https://orwellfoundation.com',
    character: 'Orwell, Baldwin, Woolf, Emerson, Montaigne — the foundational essays of the form.',
    primaryGenres: ['Life & Personal Experience', 'Arts, Culture & Language', 'Society, Politics & History', 'Special Collections'],
    type: 'essay',
    fetchable: false,
    paywalled: false,
  },
];

// Source lookup by id:
export const SOURCE_MAP = Object.fromEntries(
  ALL_SOURCES.map(s => [s.id, s])
);

// Sources that can be live-fetched:
export const FETCHABLE_SOURCES = ALL_SOURCES.filter(s => s.fetchable);

// Sources used for seed data only:
export const SEED_SOURCES = ALL_SOURCES.filter(s => !s.fetchable);
