export interface SafarDestination {
  id: string;
  name: string;
  nameHindi: string;
  country: string;
  type: 'indian' | 'global';
  tagline: string;
  travelerType: string;
  imageUrl: string;
  bestTime: string;
  why_visit: string;
  history: string;
  cuisine: string;
  culture_craft: string;
  architecture: string;
  hidden_gem: string;
  amazing_facts: string[];
  emotional_vibe: string;
}

export const INDIAN_DESTINATIONS: SafarDestination[] = [
  {
    id: 'varanasi',
    name: 'Varanasi',
    nameHindi: 'वाराणसी',
    country: 'India',
    type: 'indian',
    tagline: 'The oldest living city on Earth',
    travelerType: 'For the Soul Seeker',
    imageUrl: '/images/safar/varanasi.png',
    bestTime: 'October to March',
    why_visit: 'Varanasi - also called Kashi, the City of Light - is a place where the spiritual and physical worlds meet seamlessly. It is one of the most powerful destinations for someone seeking to understand the core of Indian mysticism, death, and liberation.',
    history: 'Varanasi has been continuously inhabited for at least 3,000 years, making it one of the oldest cities in human history. It has survived empires, raids, and the passage of ages, serving as a center of Sanskrit scholarship, poetry, and philosophy for millennia. Great saints like Kabir, Tulsidas, and Ravidas lived and wrote here.',
    cuisine: 'The food here is simple yet deeply satisfying, heavily featuring local street fare. From the legendary Tamatar Chaat and Kachori Sabzi to the sweet, frothy Malaiyo and the famous Banarasi Paan, the city offers a rich tapestry of vegetarian delights.',
    culture_craft: 'Varanasi is famous for its intricate Banarasi silk weaving, a tradition passed down through generations of local families. The city is also a major center for classical Indian music, particularly the Banaras Gharana of sitar, shehnai, and tabla players.',
    architecture: 'The architecture is defined by the stone steps of the ghats that descend to the holy Ganges. The old town is a labyrinth of narrow, towering gallis built to capture the breeze, with ancient stone temples like the Kashi Vishwanath tucked away inside.',
    hidden_gem: 'Lalita Ghat houses the Nepalese Temple, a stunning wooden pagoda featuring intricate carvings in the traditional Kathmandu style, representing a peaceful cross-cultural connection.',
    amazing_facts: [
      'It is believed that dying in Kashi grants moksha, breaking the cycle of reincarnation.',
      'The cremation fires at Manikarnika Ghat have been burning continuously for thousands of years.',
      'Mark Twain wrote that Benares is older than history, older than tradition, older even than legend.'
    ],
    emotional_vibe: 'Life and death wash against each other like waves on stone steps. Here, eternity is not a concept; it is the morning fog rising from the river.'
  },
  {
    id: 'jaisalmer',
    name: 'Jaisalmer',
    nameHindi: 'जैसलमेर',
    country: 'India',
    type: 'indian',
    tagline: 'The Golden City of the Thar Desert',
    travelerType: 'For the Desert Dreamer',
    imageUrl: '/images/safar/jaisalmer.png',
    bestTime: 'November to February',
    why_visit: 'Jaisalmer rises like a sandstone mirage from the heart of the Thar Desert. Its honey-colored fort, ornate havelis, and vast sand dunes make it a stunning monument to medieval trade, chivalry, and desert folklore.',
    history: 'Founded in 1156 CE by the Rajput ruler Rawal Jaisal, the city grew wealthy as a crucial stopover on the overland trade routes linking India with Central Asia, Persia, and the West. When shipping lanes opened up in the British era, the land route declined, freezing the city in time.',
    cuisine: 'Desert cuisine is characterized by ingredients that can survive arid conditions. Savor Ker Sangri (desert berries and beans), Laal Maas (spicy mutton), and Gatte ki Sabzi, paired with rich, clarified butter-soaked flatbreads.',
    culture_craft: 'The local Manganiyar community fills the desert air with haunting folk music played on the kamayacha. The markets are filled with vibrant mirror-work embroidery, leather goods, and hand-woven camel hair rugs.',
    architecture: 'The Jaisalmer Fort is a living castle, housing a quarter of the old city\'s population. Built from yellow sandstone without mortar, its walls glow a deep gold at sunset, matching the surrounding sands.',
    hidden_gem: 'Kuldhara is an abandoned, ghost village on the outskirts of Jaisalmer, said to have been deserted overnight in the 19th century by Paliwal Brahmins fleeing an oppressive minister.',
    amazing_facts: [
      'Jaisalmer Fort is one of the very few fully "living forts" in the world, with shops and homes inside.',
      'The entire city is constructed using yellow sandstone, giving it a uniform golden appearance.',
      'The fort contains a labyrinth of seven interconnected Jain temples dating from the 12th century.'
    ],
    emotional_vibe: 'The desert winds whistle through sand-carved stone. In the silence of the dunes, you realize how brief our empires are.'
  },
  {
    id: 'hampi',
    name: 'Hampi',
    nameHindi: 'हम्पी',
    country: 'India',
    type: 'indian',
    tagline: 'Ruins of the forgotten empire',
    travelerType: 'For the Ruins Explorer',
    imageUrl: '/images/safar/hampi.png',
    bestTime: 'October to February',
    why_visit: 'Hampi is a surreal dreamscape of red boulders and ancient stone structures scattered across a vast green valley. It offers a haunting look into the peak of medieval southern Indian art, wealth, and power.',
    history: 'Hampi was the capital of the Vijayanagara Empire, one of the richest empires in medieval times. In the 15th and 16th centuries, it attracted traders from Persia, Portugal, and Italy, before being sacked and abandoned in 1565 CE.',
    cuisine: 'The surrounding area serves traditional Karnataka meals. Enjoy comforting Jolada Rotti, spicy curries, and local street food like mirchi bajji, along with fresh coconut water.',
    culture_craft: 'The local lambadi embroidery is a colorful textile craft of mirrors and threads. The ruins also host the annual Hampi Utsav, celebrating classical music and dance against the backdrop of the illuminated monuments.',
    architecture: 'The architecture is a brilliant blend of Dravidian stone carving and Islamic arches. The Virupaksha Temple remains active, while the stone chariot of the Vittala Temple stands as a masterpiece of structural precision.',
    hidden_gem: 'The Sanapur Lake, surrounded by massive granite boulders, offers a quiet retreat for coracle (circular boat) rides away from the main temple complexes.',
    amazing_facts: [
      'The Vittala Temple contains "musical pillars" that produce different notes when tapped.',
      'Hampi\'s ruins are spread over 4,100 hectares, containing over 1,600 surviving monuments.',
      'In Hindu mythology, Hampi is identified as Kishkindha, the legendary monkey kingdom of the Ramayana.'
    ],
    emotional_vibe: 'Monoliths sit silently under a vast sky, reminding us of a time when stones spoke and empires were carved by hand.'
  },
  {
    id: 'mcleodganj',
    name: 'McLeod Ganj',
    nameHindi: 'मैक्लोडगंज',
    country: 'India',
    type: 'indian',
    tagline: 'Little Lhasa in the Himalayas',
    travelerType: 'For the Peaceful Hiker',
    imageUrl: '/images/safar/mcleodganj.png',
    bestTime: 'March to June, September to November',
    why_visit: 'McLeod Ganj is the home of the Dalai Lama and the center of the Tibetan community in exile. Set against the snow-capped Dhauladhar range, it combines spiritual contemplation, mountain trails, and a unique multicultural energy.',
    history: 'Originally established as a British colonial sanatorium, the town took on a new life in 1960 when the 14th Dalai Lama fled Tibet and established his headquarters here, turning it into a global hub for Tibetan culture and Buddhism.',
    cuisine: 'The local food is a delicious blend of Tibetan and Himachali flavors. Indulge in hot momos, Thukpa (noodle soup), Thenthuk, and butter tea in cozy mountain cafes.',
    culture_craft: 'The town is a center for traditional Tibetan arts, including thangka painting, woodcarving, and weaving. The Norbulingka Institute nearby is dedicated to preserving these ancient cultural traditions.',
    architecture: 'The architecture is simple and functional, dominated by monasteries like the Tsuglagkhang Complex. Prayer flags flutter from roofs and pine trees, adding color to the mist-shrouded hills.',
    hidden_gem: 'The walk to Dharamkot, a quiet village further up the mountain, offers pine-scented paths and a slower, more bohemian lifestyle.',
    amazing_facts: [
      'It is the seat of the Tibetan Government-in-Exile, representing Tibetans globally.',
      'The town is the starting point for the Triund trek, which offers panoramic views of the Dhauladhar peaks.',
      'The local St. John in the Wilderness church is a neo-gothic stone church dating back to 1852.'
    ],
    emotional_vibe: 'Pine needles cushion your steps as bells ring in the mist. Here, peace is not found; it is breathed in.'
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    nameHindi: 'पुदुच्चेरी',
    country: 'India',
    type: 'indian',
    tagline: 'The French Riviera of the East',
    travelerType: 'For the Quiet Stroller',
    imageUrl: '/images/safar/pondicherry.png',
    bestTime: 'October to March',
    why_visit: 'Pondicherry is a charming seaside town where French colonial elegance meets Tamil heritage. Its pastel-colored streets, quiet beaches, and spiritual communities make it a unique sanctuary of peace and history.',
    history: 'Originally a French colonial settlement until 1954, "Pondy" has preserved its French layout, language, and architecture. In 1926, Sri Aurobindo and Mirra Alfassa (The Mother) founded the Sri Aurobindo Ashram here, transforming its cultural identity.',
    cuisine: 'The food is a delightful French-Tamil fusion. Enjoy fresh croissants, ratatouille, crepes, and wood-fired pizzas alongside spicy fish curries and traditional filter coffee.',
    culture_craft: 'Handmade paper, terracotta pottery, and organic perfumes are local specialties. Nearby Auroville is an experimental township dedicated to human unity and sustainable living practices.',
    architecture: 'The town is split into the French Quarter, with its mustard-yellow colonial mansions, arched windows, and bougainvillea-laden walls, and the Tamil Quarter, featuring traditional wooden verandas and courtyards.',
    hidden_gem: 'Serenity Beach, located a few kilometers north, is a quiet stretch of golden sand perfect for watching fishermen launch their boats at dawn.',
    amazing_facts: [
      'Auroville is a township where people from over 50 countries live without money or politics.',
      'The French language is still spoken by many residents, and street names are written in French and Tamil.',
      'The Matrimandir in Auroville is a giant golden sphere containing a silent meditation chamber.'
    ],
    emotional_vibe: 'Bicycles lean against yellow walls as the sea breeze rolls in. The past lingers here like a afternoon conversation.'
  },
  {
    id: 'orchha',
    name: 'Orchha',
    nameHindi: 'ओरछा',
    country: 'India',
    type: 'indian',
    tagline: 'The hidden architectural gem of Bundelkhand',
    travelerType: 'For the History Lover',
    imageUrl: '/images/safar/orchha.png',
    bestTime: 'October to March',
    why_visit: 'Orchha is a sleepy town on the banks of the Betwa River, dotted with massive stone palaces, temples, and cenotaphs. It offers a rare, tourist-free glimpse into the artistic height of the Bundela Rajput dynasty.',
    history: 'Founded in 1501 CE by the Bundela chief Rudra Pratap Singh, Orchha was the capital of a powerful kingdom. Its rulers maintained a complex relationship with the Mughal Empire, leading to unique architectural collaborations.',
    cuisine: 'Enjoy rich Central Indian dishes like Dal Bafla (baked wheat balls in lentil curry), Mawa Bati (a rich sweet), and local river fish prepared with aromatic Bundeli spices.',
    culture_craft: 'The town is famous for Dokra metal casting and traditional block-printed textiles. The temples still echo with devotional singing, particularly at the Ram Raja Temple.',
    architecture: 'The structures are monumental, featuring massive stone domes, open-air courtyards, and delicate stone screens. The Jahangir Mahal is a spectacular palace built to welcome a single visit from the Mughal Emperor Jahangir.',
    hidden_gem: 'The Betwa River sanctuary offers peaceful walking trails and views of the chhatris (cenotaphs) reflecting in the quiet water at sunset.',
    amazing_facts: [
      'The Ram Raja Temple is the only temple in India where Lord Ram is worshipped as a king rather than a deity.',
      'Jahangir Mahal was used by the Mughal Emperor Jahangir for only one night before being abandoned.',
      'The murals inside the Laxminarayan Temple depict an intriguing mix of religious and secular historical scenes.'
    ],
    emotional_vibe: 'Massive stone walls crumble quietly into the river. History here is not in museums; it is the ground you walk on.'
  },
  {
    id: 'majuli',
    name: 'Majuli',
    nameHindi: 'माजुली',
    country: 'India',
    type: 'indian',
    tagline: 'The largest river island in the world',
    travelerType: 'For the Culture Enthusiast',
    imageUrl: '/images/safar/majuli.png',
    bestTime: 'October to March',
    why_visit: 'Majuli is a green, quiet island in the middle of the mighty Brahmaputra River. It is a sanctuary of Assamese neo-Vaishnavite culture, traditional mask-making, and peaceful rural living.',
    history: 'Formed due to changes in the course of the Brahmaputra River in the 17th century, Majuli became the center of the cultural movement led by the saint Srimanta Sankardeva, who established monasteries called Satras.',
    cuisine: 'The food is based on local river fish, organic rice, and fresh vegetables. Try Komal Saul (a traditional rice that needs no cooking, only soaking) and local rice beer prepared by the Mising tribe.',
    culture_craft: 'The Chamaguri Satra is famous for preserving the ancient art of making traditional masks from bamboo and clay, used in local religious theater called Bhaona.',
    architecture: 'The Satras are traditional wooden structures built around central prayer halls called Namghars. The local tribal homes are built on raised bamboo stilts to protect against the annual river floods.',
    hidden_gem: 'The wetlands of Majuli are a paradise for birdwatchers, attracting migratory birds like the Siberian Crane and Greater Adjutant Stork during winter.',
    amazing_facts: [
      'Majuli is the first island in India to be made a complete administrative district.',
      'Due to river erosion, the island has shrunk significantly over the last century, making it a fragile ecosystem.',
      'The island has been the cultural capital of Assamese civilization for over five centuries.'
    ],
    emotional_vibe: 'Water and soil shift under a vast Assam sky. Life here is lived to the rhythm of the river\'s rise and fall.'
  },
  {
    id: 'coorg',
    name: 'Coorg',
    nameHindi: 'कूर्ग',
    country: 'India',
    type: 'indian',
    tagline: 'The Scotland of India',
    travelerType: 'For the Nature Wanderer',
    imageUrl: '/images/safar/coorg.png',
    bestTime: 'October to April',
    why_visit: 'Coorg (or Kodagu) is a lush highland region of mist-covered hills, spice plantations, and dense forests. It is a haven for coffee lovers, hikers, and those seeking to experience the distinct culture of the Kodava people.',
    history: 'Coorg maintained its independence under local Haleri kings before being annexed by the British in 1834. The Kodavas, a warrior community, have preserved their unique customs, dress, and land tenure systems for centuries.',
    cuisine: 'The food is legendary, characterized by the use of local wild spices, coconut, and rice. The signature dish is Pandi Curry (spicy pork cooked with kachampuli, a local dark vinegar), served with Kadambuttu (steamed rice balls).',
    culture_craft: 'The Kodavas celebrate festivals like Kailpodh (worship of weapons) and Huttari (harvest). The region is also famous for its organic coffee, pepper, and local cardamom.',
    architecture: 'The traditional houses, called Mundmane, feature large central courtyards, heavy wooden pillars, and tiled roofs designed to withstand the torrential monsoon rains.',
    hidden_gem: 'Chelavara Falls, a hidden waterfall cascading down a rock face, offers a quiet alternative to the busier Abbey Falls.',
    amazing_facts: [
      'Coorg is one of the largest coffee-producing districts in India, introduced by the British in the 19th century.',
      'The Kodavas are the only community in India allowed to carry firearms without a license, due to their martial heritage.',
      'The source of the sacred Kaveri River lies in the hills of Coorg at Talakaveri.'
    ],
    emotional_vibe: 'The smell of wet coffee blossoms fills the cool air. The mist rolls over the ridge, hiding the world below.'
  },
  {
    id: 'spiti-valley',
    name: 'Spiti Valley',
    nameHindi: 'स्पीति घाटी',
    country: 'India',
    type: 'indian',
    tagline: 'The middle land between earth and sky',
    travelerType: 'For the Adventurous Nomad',
    imageUrl: '/images/safar/spiti-valley.png',
    bestTime: 'June to September',
    why_visit: 'Spiti is a cold desert valley of stark, wind-carved mountains and ancient Buddhist monasteries. It is one of the most remote and visually spectacular regions in India, offering a journey into pure mountain silence.',
    history: 'Bordering Tibet, Spiti has historically been a cultural bridge. It was ruled by local kings under the influence of Ladakh and Tibet, preserving its distinct Vajrayana Buddhist culture through centuries of isolation.',
    cuisine: 'The local diet is simple and warming. Enjoy hot bowls of Thukpa, steamed momos, tsampa (roasted barley flour), and seabuckthorn tea, a local berry rich in vitamins.',
    culture_craft: 'The region is famous for hand-knitted woolen goods, carpets, and traditional metalwork. Monks at local monasteries perform sacred Cham dances during festivals.',
    architecture: 'Monasteries like Key and Tabo are architectural marvels, built like fortresses on steep cliffs. The white mud-brick houses feature flat roofs to catch the scarce sun and resist the winter snows.',
    hidden_gem: 'Dhankar Lake, a high-altitude lake located a steep hike above the Dhankar monastery, offers absolute silence and reflection.',
    amazing_facts: [
      'Tabo Monastery was founded in 996 CE, making it one of the oldest continuously functional monasteries in India.',
      'Hikkim village in Spiti contains the highest functional post office in the world at 14,400 feet.',
      'Spiti is home to the rare Snow Leopard, Himalayan Wolf, and Blue Sheep.'
    ],
    emotional_vibe: 'Stark mountains rise into a deep, cloudless blue. The wind carries the scent of juniper and ancient stones.'
  },
  {
    id: 'chettinad',
    name: 'Chettinad',
    nameHindi: 'चेट्टिनाड',
    country: 'India',
    type: 'indian',
    tagline: 'The land of heritage mansions and spice',
    travelerType: 'For the Culinary & Design Connoisseur',
    imageUrl: '/images/safar/chettinad.png',
    bestTime: 'October to March',
    why_visit: 'Chettinad is a region of quiet villages famous for their massive, palatial 19th-century mansions and one of the most aromatic, complex culinary traditions in southern India.',
    history: 'The region was built by the Nattukottai Chettiars, a wealthy merchant community who traveled across Southeast Asia. They channeled their fortunes into building spectacular family mansions in their dry ancestral villages.',
    cuisine: 'Chettinad cuisine is famous for its complex spice blends, using fresh pepper, star anise, and kalpasi (stone flower). Enjoy Chettinad Pepper Chicken, Kuzhi Paniyaram, and soft idiyappams.',
    culture_craft: 'Athangudi tiles, handmade using local sand and cement in vibrant geometric patterns, are a famous local craft. The markets also offer traditional Kanjivaram-style Chettinad cotton saris.',
    architecture: 'The mansions are architectural wonders, using teak wood from Burma, marble from Italy, and mirrors from Belgium. They feature grand central courtyards designed for family gatherings and rainwater harvesting.',
    hidden_gem: 'The Athangudi tile-making workshops, where you can watch craftsmen create intricate tile patterns by hand using traditional stencils.',
    amazing_facts: [
      'Some mansions here have over 100 rooms, spanning entire city blocks.',
      'The walls of the mansions were polished using egg whites and lime to give them a permanent shell-like shine.',
      'The Chettiars were pioneers in traditional banking systems in southern India.'
    ],
    emotional_vibe: 'Dust motes float in empty, teak-lined halls. The grandeur of the past sits quietly in the afternoon heat.'
  },
  {
    id: 'gokarna',
    name: 'Gokarna',
    nameHindi: 'गोकर्ण',
    country: 'India',
    type: 'indian',
    tagline: 'Where the temples meet the sea',
    travelerType: 'For the Beach Solitude Seeker',
    imageUrl: '/images/safar/gokarna.png',
    bestTime: 'October to March',
    why_visit: 'Gokarna is a sleepy temple town on the Arabian Sea, flanked by pristine, crescent-shaped beaches. It offers a unique mix of Hindu pilgrimage and relaxed coastal solitude away from the crowds of Goa.',
    history: 'Gokarna is a major pilgrimage site mentioned in Hindu epics. The Mahabaleshwar Temple houses the Atmalinga, a sacred relic of Shiva. The town has preserved its traditional Sanskrit culture and priestly lineages for centuries.',
    cuisine: 'Enjoy fresh seafood, traditional Kannada vegetarian meals, and the famous "Nutella pancake" culture found in the beachside shacks.',
    culture_craft: 'The town is famous for brass lamps, hand-carved wooden deities, and local spice markets. Traditional Sanskrit chants echo through the town during major festivals.',
    architecture: 'The town houses feature sloping tiled roofs and wooden pillars. The beaches are accessible via scenic hikes over rocky cliffs, offering spectacular ocean panoramas.',
    hidden_gem: 'Half Moon Beach, a secluded cove accessible only by boat or a hike through the forest, offers absolute privacy.',
    amazing_facts: [
      'Gokarna means "cow\'s ear", referring to the shape of the confluence of two local rivers.',
      'The Atmalinga temple is believed to have been established by Ravana himself.',
      'The beaches here are situated along the Western Ghats, where the mountains meet the sea.'
    ],
    emotional_vibe: 'The temple bells ring as the sun sinks into the sea. The sand is cool, and the water is warm.'
  },
  {
    id: 'zanskar',
    name: 'Zanskar',
    nameHindi: 'जांस्कर',
    country: 'India',
    type: 'indian',
    tagline: 'The wild valley of ice and stone',
    travelerType: 'For the Mountain Mystic',
    imageUrl: '/images/safar/zanskar.png',
    bestTime: 'June to September',
    why_visit: 'Zanskar is a spectacular, high-altitude valley of jagged peaks, hanging glaciers, and ancient monasteries built into cliffs. It represents the ultimate frontier of Himalayan wilderness and solitude.',
    history: 'Part of the ancient kingdom of Guge, Zanskar remained isolated from the outside world for centuries due to high mountain passes. This isolation preserved a pure form of Tibetan Buddhist culture and lifestyle.',
    cuisine: 'The mountain diet relies on barley, dairy, and local root vegetables. Try butter tea (Gur-Gur), Skyu (traditional pasta stew), and local dried cheese.',
    culture_craft: 'The valley is known for hand-woven woolens, metal singing bowls, and traditional thangka embroidery. Monasteries host annual monastic festivals featuring mask dances.',
    architecture: 'The Phugtal Monastery is one of the most spectacular sights in the Himalayas, built around a natural cave on a sheer cliff face over a rushing river.',
    hidden_gem: 'The village of Anmu, a tiny green oasis surrounded by massive barren mountains, offers a look into traditional farming life.',
    amazing_facts: [
      'In winter, the frozen Zanskar River becomes the "Chadar Trek", the only way in or out of the valley.',
      'Phugtal Monastery was founded in the 12th century and is accessible only on foot.',
      'The valley is snowbound for nearly six months of the year, cut off from the rest of India.'
    ],
    emotional_vibe: 'Ice meets stone under a silent sky. The river roars in the canyon, and the wind speaks in prayer.'
  },
  {
    id: 'mahabalipuram',
    name: 'Mahabalipuram',
    nameHindi: 'महाबलीपुरम',
    country: 'India',
    type: 'indian',
    tagline: 'Monuments carved from rock by the sea',
    travelerType: 'For the Art and Sea Lover',
    imageUrl: '/images/safar/mahabalipuram.png',
    bestTime: 'October to March',
    why_visit: 'Mahabalipuram (or Mamallapuram) is a historic town on the Bay of Bengal, famous for its grand 7th-century rock-cut monuments, monolithic temples, and active stone-carving traditions.',
    history: 'A major port city of the Pallava dynasty in the 7th and 8th centuries, Mahabalipuram was a center from which Indian art, architecture, and religion spread to Southeast Asia, influencing temple styles in Java and Cambodia.',
    cuisine: 'The town is a paradise for fresh seafood lovers. Enjoy grilled fish, spicy prawns, and traditional Tamil meals served on banana leaves.',
    culture_craft: 'The town is a living workshop of stone sculpture. The streets echo with the sound of hammers and chisels, a tradition maintained by modern masters who train at the local college of traditional sculpture.',
    architecture: 'The Shore Temple stands at the water\'s edge, designed to catch the first rays of the rising sun. The Pancha Rathas are five monolithic structures carved from single massive boulders.',
    hidden_gem: 'The Tiger Cave, a quiet rock-cut shrine located in a green park north of the town, offers a peaceful alternative to the main temple complex.',
    amazing_facts: [
      'Krishna\'s Butterball is a massive boulder that sits on a steep slope, defying gravity for centuries.',
      'The Descent of the Ganges is one of the largest open-air relief carvings in the world.',
      'Local fishermen reported seeing ruins of submerged temples offshore during the 2004 tsunami.'
    ],
    emotional_vibe: 'Salt spray wears away ancient stone. The wind whispers stories of sailors who returned to these temples.'
  },
  {
    id: 'mandu',
    name: 'Mandu',
    nameHindi: 'मांडू',
    country: 'India',
    type: 'indian',
    tagline: 'The fortress of love and monsoon poetry',
    travelerType: 'For the Romantic Historian',
    imageUrl: '/images/safar/mandu.png',
    bestTime: 'July to September (monsoon is best)',
    why_visit: 'Mandu is an ancient, ruined fortress city perched on a green plateau in Madhya Pradesh. Famous for its Afghan architecture, grand palaces, and the legendary love story of Baz Bahadur and Roopmati, it is particularly magical during the monsoon rains.',
    history: 'Mandu grew to prominence in the 10th century as a fortress city. In the 15th and 16th centuries, under Muslim rulers, it became a center of art and architecture, culminating in the reign of Baz Bahadur, the last independent ruler.',
    cuisine: 'Enjoy traditional Malwa cuisine, including Dal Bafla, Bhutte ka Kees (grated corn cooked with spices), and Mawa Bati, along with local varieties of mangoes.',
    culture_craft: 'The local tribal communities of Dhar district create beautiful Bagh block prints, a traditional hand-block printing technique using natural vegetable dyes.',
    architecture: 'The architecture is characterized by massive stone structures with elegant domes and arches. The Jahaz Mahal (Ship Palace) is built between two lakes, appearing like a grand ship floating in water during the rains.',
    hidden_gem: 'The Nilkanth Palace, a quiet stone temple built on the edge of a deep valley, offers panoramic views of the plains below.',
    amazing_facts: [
      'Jahaz Mahal was built to house a harem of 15,000 women for Sultan Ghiyas-ud-din.',
      'The Hindola Mahal (Swinging Palace) features sloping walls that give the illusion of a swinging structure.',
      'The tomb of Hoshang Shah is believed to be India\'s first marble structure, which inspired the Taj Mahal.'
    ],
    emotional_vibe: 'Monsoon clouds drape over stone arches. The rain speaks of old love songs sung in empty palaces.'
  },
  {
    id: 'tawang',
    name: 'Tawang',
    nameHindi: 'तवांग',
    country: 'India',
    type: 'indian',
    tagline: 'The monastery in the clouds',
    travelerType: 'For the Sacred Peak Explorer',
    imageUrl: '/images/safar/tawang.png',
    bestTime: 'March to May, September to November',
    why_visit: 'Tawang is a high-altitude town in Arunachal Pradesh, home to the second-largest Buddhist monastery in the world. Set against snow-covered peaks, it offers spectacular natural beauty and deep spiritual heritage.',
    history: 'Originally part of Tibet, the region became part of India in 1914. Tawang Monastery was founded in 1681 CE in accordance with the wishes of the 5th Dalai Lama, and remains a major center of Mahayana Buddhism.',
    cuisine: 'The local food includes Momos, Thukpa, and Zan (a savory porridge of finger millet). Try the local yak cheese (chhurpi) cooked with spices and wild vegetables.',
    culture_craft: 'The Monpa people are famous for traditional carpet weaving, handmade paper (mon shugu), and woodcrafts. The Torgya festival is celebrated with spectacular masked dances.',
    architecture: 'Tawang Monastery is a massive, fortified complex housing over 300 monks. Its three-story assembly hall contains an 18-foot golden Buddha statue surrounded by ancient murals.',
    hidden_gem: 'The Sangetsar Lake (popularly called Madhuri Lake), formed after an earthquake, features dead tree trunks standing out of the clear water, surrounded by mountains.',
    amazing_facts: [
      'Tawang Monastery is the largest monastery in India and the second-largest in the world after the Potala Palace.',
      'The 6th Dalai Lama, Tsangyang Gyatso, was born in the Tawang Valley in 1683.',
      'The road to Tawang passes through the spectacular Sela Pass at 13,700 feet.'
    ],
    emotional_vibe: 'Clouds flow through the monastery gates. The sound of horns echoes off the snow peaks.'
  },
  {
    id: 'khajuraho',
    name: 'Khajuraho',
    nameHindi: 'खजुराहो',
    country: 'India',
    type: 'indian',
    tagline: 'The expression of life in stone',
    travelerType: 'For the Sculpture Admirer',
    imageUrl: '/images/safar/khajuraho.png',
    bestTime: 'October to February',
    why_visit: 'Khajuraho is famous for its UNESCO-listed group of temples, celebrated for their intricate, expressive, and sensual carvings that celebrate all aspects of human life, divinity, and nature.',
    history: 'Built by the Chandela Rajput dynasty between 950 and 1050 CE, the temples were abandoned after the fall of the dynasty and preserved by the surrounding forests. They were rediscovered by British officer T.S. Burt in 1838.',
    cuisine: 'Savor Bundelkhand delicacies like Biryani, Rogan Josh, and local sweets like Jalebi and Rabdi, widely available in the village markets.',
    culture_craft: 'The annual Khajuraho Dance Festival in February brings together the country\'s finest classical dancers performing against the backdrop of the illuminated temples.',
    architecture: 'The temples are built in the Nagara style, rising in spiraling spires that mimic the peaks of the sacred Mount Kailash. The carvings are executed in fine-grained sandstone with extraordinary detail.',
    hidden_gem: 'The Javari Temple, a small but beautifully proportioned temple in the East Group, offers a quiet space away from the main Western Group crowds.',
    amazing_facts: [
      'Of the original 85 temples, only 25 have survived the passage of time.',
      'Contrary to popular belief, only about 10% of the carvings are erotic; the rest show daily life and divinity.',
      'The Kandariya Mahadeva temple is the largest, featuring over 800 detailed figures on its walls.'
    ],
    emotional_vibe: 'Sandstone figures twist and dance in the sun. Here, the sacred and the sensual are one.'
  },
  {
    id: 'lepakshi',
    name: 'Lepakshi',
    nameHindi: 'लेपाक्षी',
    country: 'India',
    type: 'indian',
    tagline: 'The hanging pillar and legendary stone carvings',
    travelerType: 'For the Mystery Seeker',
    imageUrl: '/images/safar/lepakshi.png',
    bestTime: 'September to February',
    why_visit: 'Lepakshi is a small historical village in Andhra Pradesh, home to the spectacular Veerabhadra Temple. It is a masterpiece of late Vijayanagara art, famous for its hanging pillar and legendary rock-cut monoliths.',
    history: 'Built in the 16th century by two brothers, Virupanna and Veeranna, who were governors under the Vijayanagara Empire. The temple was built on a low rocky hill shaped like a tortoise, called Kurmasaila.',
    cuisine: 'Enjoy traditional Andhra meals, including spicy Pappu (lentils), Avakaya (mango pickle), and Gongura pachadi, served with hot rice and ghee.',
    culture_craft: 'The local area is known for wooden toys and handloom weaving. The temple itself is a major reference point for traditional south Indian textile patterns and designs.',
    architecture: 'The Veerabhadra Temple contains spectacular stone pillars carved with musicians and dancers. The ceiling is decorated with massive, beautifully preserved murals illustrating scenes from Hindu mythology.',
    hidden_gem: 'The giant monolithic Nandi (Shiva\'s bull), located a short walk from the temple, is carved from a single massive granite boulder and is one of the largest in India.',
    amazing_facts: [
      'The temple has a famous "hanging pillar" that does not touch the ground, allowing paper to pass under it.',
      'A massive unfinished kalyana mandapa (marriage hall) stands roofless, its pillars frozen mid-carving.',
      'The temple murals are among the finest surviving examples of Vijayanagara painting.'
    ],
    emotional_vibe: 'Pillars of solid granite hang suspended in space. The stone whispers of old builders and unfinished dreams.'
  },
  {
    id: 'dholavira',
    name: 'Dholavira',
    nameHindi: 'धोलावीरा',
    country: 'India',
    type: 'indian',
    tagline: 'The water city of the Indus Valley',
    travelerType: 'For the Archaeology Scholar',
    imageUrl: '/images/safar/dholavira.png',
    bestTime: 'November to February',
    why_visit: 'Dholavira, located on the island of Khadir Bet in the Great Rann of Kutch, is one of the most significant ruins of the ancient Indus Valley Civilization. It represents the height of ancient urban planning, masonry, and water management.',
    history: 'Inhabited from 2650 BCE to 1900 BCE, Dholavira was a thriving metropolis that traded with Mesopotamia. It was discovered by archaeologist J.P. Joshi in 1967 and excavated in the 1990s, revealing a highly sophisticated society.',
    cuisine: 'Try traditional Kutchi cuisine, including Bajra roti (pearl millet bread), Ringan No Oro (roasted eggplant), Kadi, and sweet Khichdi, prepared with fresh buttermilk.',
    culture_craft: 'The surrounding Rann of Kutch is famous for Rogan art, leather embroidery, and woolen weaving. In winter, the Rann Utsav celebrating local music and dance takes place nearby.',
    architecture: 'The city was constructed entirely using dressed stone, unlike the brick cities of Harappa and Mohenjo-daro. It featured a Citadel, a Middle Town, and a Lower Town, surrounded by massive fortifications.',
    hidden_gem: 'The ancient fossil park, located on the edge of the island, containing petrified tree trunks dating back 180 million years.',
    amazing_facts: [
      'Dholavira had a spectacular system of sixteen massive stone-cut water reservoirs to survive the arid climate.',
      'The site yielded a "signboard" containing ten large Indus script characters, one of the longest inscriptions known.',
      'The ruins include a massive open-air stadium, the oldest known public stadium in the world.'
    ],
    emotional_vibe: 'White salt flats stretch to the horizon. In the ruins of stone reservoirs, the wind whispers of ancient engineers.'
  },
  {
    id: 'pattadakal',
    name: 'Pattadakal',
    nameHindi: 'पट्टदकल',
    country: 'India',
    type: 'indian',
    tagline: 'The crown jewel of Chalukyan architecture',
    travelerType: 'For the Architecture Devotee',
    imageUrl: '/images/safar/pattadakal.png',
    bestTime: 'October to March',
    why_visit: 'Pattadakal, a UNESCO World Heritage site in Karnataka, is a beautiful complex of 7th and 8th-century temples that represent the peak of early Indian temple architecture, where northern and southern styles merged.',
    history: 'Pattadakal was the ceremonial site where the kings of the Chalukya dynasty were crowned. It served as a holy laboratory of architectural experimentation, built along the sacred Malaprabha River.',
    cuisine: 'Indulge in North Karnataka specialties like Jolada Rotti, spicy Shenga Chutney (peanut chutney), and local vegetable curries, accompanied by fresh curd.',
    culture_craft: 'The nearby towns of Ilkal and Guledgudda are famous for their traditional handloom saris, characterized by distinct borders and designs that have been woven for centuries.',
    architecture: 'The complex features nine Hindu temples and one Jain sanctuary. The Virupaksha Temple, built by Queen Lokamahadevi in 740 CE, is a masterpiece of sculpture, featuring detailed narratives from Indian epics.',
    hidden_gem: 'The Papanatha Temple, located slightly away from the main group, exhibits a unique mixture of northern Nagara and southern Dravidian architectural elements.',
    amazing_facts: [
      'The temple complex represents the cradle of temple architecture in southern India.',
      'Virupaksha Temple was the source of inspiration for the famous Kailash Temple in Ellora.',
      'The sculptures include detailed depictions of daily life, fashion, and social customs of the 8th century.'
    ],
    emotional_vibe: 'Temples of red sandstone catch the morning light. The river flows slowly, carrying the memory of kings.'
  },
  {
    id: 'kumarakom',
    name: 'Kumarakom',
    nameHindi: 'कुमारकोम',
    country: 'India',
    type: 'indian',
    tagline: 'The silent life of the backwaters',
    travelerType: 'For the Tranquil Cruiser',
    imageUrl: '/images/safar/kumarakom.png',
    bestTime: 'September to March',
    why_visit: 'Kumarakom is a cluster of little islands on the Vembanad Lake in Kerala. It offers a tranquil escape into the slow life of the backwaters, surrounded by canals, houseboats, and bird sanctuaries.',
    history: 'Much of the land here was reclaimed from the lake in the 19th century by English farmer George Alfred Baker, who established coconut and rubber plantations. Today, it has transitioned into a world-class eco-tourism destination.',
    cuisine: 'Kerala backwater cuisine is famous for Karimeen Pollichathu (pearl spot fish marinated in spices and baked in banana leaves), prawn curry, and soft appams with stew.',
    culture_craft: 'Coir (coconut fiber) weaving, wooden houseboat construction (Kettuvallam), and traditional fishing are local skills. The annual Nehru Trophy Boat Race on the lake is a spectacular water carnival.',
    architecture: 'The local resorts feature traditional Nalukettu (four-sided courtyard houses) made of teak and jackwood, set along canals where houseboats glide silently.',
    hidden_gem: 'The Kumarakom Bird Sanctuary, where a quiet walk at dawn reveals flocks of migratory birds like the Siberian Stork nesting in the canopy.',
    amazing_facts: [
      'Vembanad Lake is the longest lake in India and the largest lake in Kerala.',
      'The traditional houseboats are built using jackwood planks tied together with coir rope without a single nail.',
      'Kumarakom is one of the very few places globally where farming is done below sea level in reclaimed land.'
    ],
    emotional_vibe: 'Water hyacinths drift slowly past the veranda. The coconut palms bend to touch their own reflections.'
  }
];

export const GLOBAL_DESTINATIONS: SafarDestination[] = [
  {
    id: 'kyoto',
    name: 'Kyoto',
    nameHindi: 'क्योतो',
    country: 'Japan',
    type: 'global',
    tagline: 'The city that remembered how to be beautiful',
    travelerType: 'For the Zen Seeker',
    imageUrl: '/images/safar/kyoto.png',
    bestTime: 'April (Cherry Blossoms) or November (Autumn)',
    why_visit: 'Kyoto was the imperial capital of Japan for over a millennium. With its thousands of temples, historic wooden townhouses, and rock gardens, it is the cultural and spiritual heart of traditional Japan.',
    history: 'Established in 794 CE as Heian-kyo, the city survived civil wars and rapid modernization. It was spared from bombing during World War II, preserving its rich architectural heritage of imperial palaces, Shinto shrines, and Buddhist temples.',
    cuisine: 'Savor traditional Kaiseki - a multi-course seasonal art form. Try Yudofu (silken tofu simmered in kelp broth), Uji matcha tea, and Yatsuhashi (cinnamon-flavored sweet rice wrappers filled with red bean paste).',
    culture_craft: 'Kyoto is the center of Japanese traditional arts, including the tea ceremony (Chado), flower arrangement (Ikebana), geisha culture (Gion district), and Nishijin silk weaving.',
    architecture: 'The architecture ranges from golden pavilions like Kinkaku-ji to traditional wooden machiya townhouses. The rock garden at Ryoan-ji represents the peak of dry landscape (karesansui) Zen garden design.',
    hidden_gem: 'The Gio-ji Temple, a tiny, quiet moss temple in the Arashiyama hills, offering a green sanctuary away from the tourist crowds.',
    amazing_facts: [
      'Kyoto has over 1,600 Buddhist temples and 400 Shinto shrines.',
      'The famous dry stone garden at Ryoan-ji contains fifteen stones, but they are arranged so that you can never see all fifteen at once from any angle.',
      'Henry Stimson, the US Secretary of War during WWII, personally had Kyoto removed from the atomic bomb target list because of its cultural value.'
    ],
    emotional_vibe: 'Maple leaves turn crimson over raked gravel. In the shadow of the temple, the modern world feels very far away.'
  },
  {
    id: 'patagonia',
    name: 'Patagonia',
    nameHindi: 'पटागोनिया',
    country: 'Argentina / Chile',
    type: 'global',
    tagline: 'Where the world runs out',
    travelerType: 'For the Wild Explorer',
    imageUrl: '/images/safar/patagonia.png',
    bestTime: 'December to March',
    why_visit: 'Patagonia is a vast, empty region at the southern tip of South America. Flanked by the Andes, it is a landscape of massive glaciers, jagged granite towers, and windswept grasslands that feel like the edge of the Earth.',
    history: 'Inhabited for over 10,000 years by indigenous Tehuelche and Kawesqar peoples, the region was mapped by Ferdinand Magellan in 1520. It remained a wild, untamed frontier occupied by sheep farmers and explorers for centuries.',
    cuisine: 'The culinary highlight is Cordero al Asador (whole lamb slow-roasted over an open fire). Pair it with local calafate berry desserts and robust Argentine Malbec wine.',
    culture_craft: 'The region preserves the gaucho (cowboy) culture of horsemanship and simple rural living. Local woolens and leather goods are crafted to withstand the harsh subantarctic winds.',
    architecture: 'The architecture is simple and rugged, dominated by tin-roofed estancias (ranches) and wooden shelters designed to survive high winds. Modern eco-lodges blend seamlessly into the mountain landscapes.',
    hidden_gem: 'The Marble Caves of Lake General Carrera, spectacular cavern walls carved by water into shades of blue and grey, accessible only by boat.',
    amazing_facts: [
      'The wind in Patagonia can blow so constantly and fiercely that trees grow bent permanently sideways.',
      'The Perito Moreno Glacier is one of the few glaciers in the world that is still stable and growing rather than retreating.',
      'Charles Darwin spent months in Patagonia during the voyage of the Beagle, collectings fossils that shaped his evolutionary ideas.'
    ],
    emotional_vibe: 'Jagged peaks rise into the cloud. The silence is broken only by the sound of glaciers cracking in the wind.'
  },
  {
    id: 'fez-morocco',
    name: 'Fez',
    nameHindi: 'फ़ेज़',
    country: 'Morocco',
    type: 'global',
    tagline: 'The living medieval labyrinth',
    travelerType: 'For the Labyrinth Wanderer',
    imageUrl: '/images/safar/fez-morocco.png',
    bestTime: 'March to May or September to November',
    why_visit: 'Fez is the cultural and spiritual capital of Morocco. Its ancient walled city, Fez el-Bali, is a dense labyrinth of over 9,000 alleys, representing the most intact medieval Islamic city in the world.',
    history: 'Founded in 789 CE by Idris I, Fez became a great intellectual center of the Mediterranean. It welcomed refugees from Spain and Tunisia, creating a rich synthesis of Andalusian and North African culture.',
    cuisine: 'Try traditional Pastilla (a sweet and savory pigeon pastry), tagines cooked with olives and preserved lemons, and mint tea served in busy street cafes.',
    culture_craft: 'The city is famous for its open-air leather tanneries (like Chouara Tannery), where leather is dyed in stone vessels using traditional methods that have not changed since the 11th century.',
    architecture: 'The buildings feature blank exterior walls that open into inner courtyards decorated with complex zellij tilework, carved stucco, and cedar wood. The Bou Inania Madrasa is a masterpiece of Marinid architecture.',
    hidden_gem: 'The gardens of Jnan Sbil, a peaceful park of palms and fountains just outside the city walls, offering respite from the sensory overload of the medina.',
    amazing_facts: [
      'Fez el-Bali is the largest contiguous car-free urban area in the world.',
      'The University of al-Qarawiyyin, founded in 859 CE, is recognized by UNESCO as the oldest continuously operating university in the world.',
      'The medina contains over 9,000 winding streets, many of which lead to dead ends.'
    ],
    emotional_vibe: 'Donkeys carry spices through narrow stone walls. The air smells of cedar wood, mint, and leather.'
  },
  {
    id: 'cappadocia',
    name: 'Cappadocia',
    nameHindi: 'कप्पाडोसिया',
    country: 'Turkey',
    type: 'global',
    tagline: 'The fairy chimney dreamscape',
    travelerType: 'For the Sky Gazing Dreamer',
    imageUrl: '/images/safar/cappadocia.png',
    bestTime: 'April to June or September to October',
    why_visit: 'Cappadocia is a geological wonder of soft volcanic rock carved by wind into towering "fairy chimneys" and honeycombed with ancient underground cities and cave churches.',
    history: 'Formed by volcanic eruptions millions of years ago, the landscape was carved by human hands. Early Christians carved out cave monasteries, churches, and entire multi-level underground cities like Derinkuyu to hide from invading armies.',
    cuisine: 'Indulge in Testi Kebabi (meat and vegetables cooked inside a sealed clay pot that is cracked open at your table) and local Anatolian wines stored in cool cave cellars.',
    culture_craft: 'The town of Avanos has been a center of red clay pottery-making since the Hittite period. Traditional hand-knotted Turkish carpets are also a major local craft.',
    architecture: 'The architecture is subterranean and rock-cut. Houses and hotels are carved directly into the soft volcanic tuff, offering cool interiors in summer and warmth in winter.',
    hidden_gem: 'The Red Valley at sunset, where the rock formations turn brilliant shades of pink and orange, offering quiet walking paths.',
    amazing_facts: [
      'Derinkuyu is an underground city that could house up to 20,000 people across 8 subterranean levels.',
      'Over 100 hot air balloons take to the sky here every morning at sunrise, creating a surreal landscape.',
      'The cave churches of Göreme Open Air Museum contain beautiful Byzantine frescoes painted directly onto the stone.'
    ],
    emotional_vibe: 'Balloons drift over pink volcanic valleys. Earth and sky merge in a landscape carved by wind and history.'
  },
  {
    id: 'iceland',
    name: 'Iceland',
    nameHindi: 'आिसलैंड',
    country: 'Iceland',
    type: 'global',
    tagline: 'The land of fire and ice',
    travelerType: 'For the Cosmic Voyager',
    imageUrl: '/images/safar/iceland.png',
    bestTime: 'June to August (Midnight Sun) or September to March (Aurora)',
    why_visit: 'Iceland is a wild island of dramatic contrasts, where active volcanoes sit next to massive ice fields, and geothermal hot springs bubble up under black sand beaches.',
    history: 'Settled by Norse Vikings in the late 9th century, Iceland has preserved its language and Viking heritage. Its parliament, the Althing, was established in 930 CE, making it the oldest parliament in the world.',
    cuisine: 'The food focuses on fresh seafood, slow-roasted mountain lamb, and Skyr (a traditional thick dairy product). Adventure seekers can try traditional fermented shark (Hákarl).',
    culture_craft: 'Iceland has a rich literary tradition of ancient sagas. Local wool is hand-knitted into traditional lopapeysa sweaters, featuring distinct geometric yoke patterns.',
    architecture: 'The architecture is simple and functional, using wood, stone, and corrugated iron to withstand the elements. Modern structures like the Harpa Concert Hall feature glass facades inspired by basalt columns.',
    hidden_gem: 'The Westfjords, a remote and spectacular region of deep fjords and bird cliffs that receives only a fraction of the country\'s tourists.',
    amazing_facts: [
      'Iceland has no mosquitoes, thanks to its unique climate and rapid weather changes.',
      'Over 85% of Iceland\'s heating and electricity comes from domestic renewable geothermal energy.',
      'According to surveys, a large portion of the population believes in the existence of Huldufólk (hidden people or elves).'
    ],
    emotional_vibe: 'Basalt pillars rise from black sand. The northern lights paint green brushstrokes across a cold, dark sky.'
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    nameHindi: 'लिस्बन',
    country: 'Portugal',
    type: 'global',
    tagline: 'The city of light, hills, and fado',
    travelerType: 'For the Melancholic Wanderer',
    imageUrl: '/images/safar/lisbon.png',
    bestTime: 'March to May or September to October',
    why_visit: 'Lisbon is a beautiful coastal city built on seven hills. Its pastel-colored buildings, tiled facades, rattling vintage trams, and soulful street music make it a romantic capital of light and nostalgia.',
    history: 'One of the oldest cities in Western Europe, Lisbon was occupied by Phoenicians, Romans, and Moors. It was the launching pad for the Age of Discovery in the 15th century, before being devastated by a massive earthquake in 1755.',
    cuisine: 'Savor Pasteis de Nata (crisp custard tarts), grilled sardines, and Bacalhau (salted cod prepared in hundreds of ways), accompanied by local Vinho Verde (green wine).',
    culture_craft: 'The city is famous for its hand-painted azulejo tiles. The soul of Lisbon is Fado - a melancholic genre of music sung in small taverns, expressing longing and fate.',
    architecture: 'The architecture features unique Manueline (Portuguese gothic) stone carving, houses covered in patterned ceramic tiles, and grand plazas. The Alfama district preserves the old Moorish street layout.',
    hidden_gem: 'The Miradouro da Graça at dusk, a quiet pine-shaded terrace offering panoramic views of the castle and the Tejo River.',
    amazing_facts: [
      'Lisbon is older than Rome, dating back to around 1200 BCE as a Phoenician trading post.',
      'The Vasco da Gama Bridge in Lisbon is the second-longest bridge in Europe, spanning over 12 kilometers.',
      'The pastel de nata recipe was created by monks at the Jerónimos Monastery in the 18th century.'
    ],
    emotional_vibe: 'Yellow trams rattle up steep cobblestone hills. The sound of a guitar drifts from an open window, carrying the sweet sorrow of fado.'
  },
  {
    id: 'chiang-mai',
    name: 'Chiang Mai',
    nameHindi: 'चियांग माई',
    country: 'Thailand',
    type: 'global',
    tagline: 'The temple city in the northern mist',
    travelerType: 'For the Slow Living Explorer',
    imageUrl: '/images/safar/chiang-mai.png',
    bestTime: 'November to February',
    why_visit: 'Chiang Mai, the former capital of the Lanna Kingdom, is a green city nestled in the mountains of northern Thailand. With its hundreds of temples, night markets, and misty hills, it is a sanctuary of northern Thai culture.',
    history: 'Founded in 1296 by King Mangrai, the city was surrounded by a defensive moat and walls to resist Burmese invasions. It functioned as the capital of the independent Lanna Kingdom for centuries before being integrated into Siam.',
    cuisine: 'The food is distinct from southern Thai cuisine, featuring rich curries and fresh herbs. Try Khao Soi (creamy coconut curry noodle soup), Sai Oua (spicy herbal sausage), and Nam Prik Ong.',
    culture_craft: 'The city is famous for traditional silverwork, woodcarving, and hand-painted paper umbrellas made in Bo Sang village. The Yi Peng lantern festival is celebrated by launching thousands of light lanterns into the night sky.',
    architecture: 'The architecture is characterized by the Lanna style - multi-tiered wooden roofs, gold-leaf carvings, and stone nagas guarding temple entrances. Wat Chedi Luang contains a massive, ancient brick chedi.',
    hidden_gem: 'Wat Pha Lat, a hidden forest temple located along the Monk\'s Trail up Doi Suthep mountain, surrounded by waterfalls and jungle.',
    amazing_facts: [
      'The old city of Chiang Mai is still surrounded by its original 700-year-old defensive moat and brick gates.',
      'There are over 300 Buddhist temples in Chiang Mai, almost as many as in Bangkok, but in a fraction of the space.',
      'Wat Phra That Doi Suthep sits at 3,500 feet, offering panoramic views of the city below.'
    ],
    emotional_vibe: 'Monks in orange robes walk quietly past old golden shrines. The evening air is cool, carrying the scent of incense.'
  },
  {
    id: 'la-paz',
    name: 'La Paz',
    nameHindi: 'ला पाज़',
    country: 'Bolivia',
    type: 'global',
    tagline: 'The city touching the sky',
    travelerType: 'For the Altitude Wanderer',
    imageUrl: '/images/safar/la-paz.png',
    bestTime: 'May to October',
    why_visit: 'La Paz is the highest administrative capital in the world, sitting in a spectacular mountain bowl at 12,000 feet. Its combination of indigenous Aymara culture, modern cable cars, and dramatic Andean views makes it a dizzying urban experience.',
    history: 'Founded in 1548 by Spanish conquistadors on the site of an indigenous settlement, the city grew as a center of administration and silver trade. It has been a hub of political and social movements throughout South American history.',
    cuisine: 'Savor traditional Salteñas (savory baked pastries filled with spiced meat and sweet broth), fricasé (spicy pork stew), and roasted trout from Lake Titicaca.',
    culture_craft: 'The streets are colorful with Aymara women wearing traditional bowler hats and pollera skirts. The Witches\' Market (Mercado de las Brujas) sells dried llama fetuses and herbal remedies for local ritual offerings.',
    architecture: 'The architecture ranges from grand colonial churches like San Francisco to "cholets" - bright, multi-story buildings that combine indigenous Andean art with modern architecture.',
    hidden_gem: 'The Valle de la Luna (Valley of the Moon), a geological park of clay obelisks and rock formations just outside the city center, carved by wind.',
    amazing_facts: [
      'La Paz is connected by Mi Teleférico, the longest and highest cable car network in the world, serving as the main public transit.',
      'At 13,325 feet, El Alto (the upper city of La Paz) is the highest major metropolitan area in the world.',
      'Water boils at 88 degrees Celsius here due to the extreme altitude and thin air.'
    ],
    emotional_vibe: 'Red brick houses climb the steep walls of the canyon. The snow-clad peak of Illimani watches over the city like a silent sentinel.'
  },
  {
    id: 'tbilisi',
    name: 'Tbilisi',
    nameHindi: 'त्बिलिसी',
    country: 'Georgia',
    type: 'global',
    tagline: 'The warm spring crossroads of continents',
    travelerType: 'For the Bohemian Wanderer',
    imageUrl: '/images/safar/tbilisi.png',
    bestTime: 'May to June or September to October',
    why_visit: 'Tbilisi, set in the deep valley of the Kura River, is a beautiful city of sulfur baths, wooden balconies, and a vibrant, art-filled lifestyle. It sits at the absolute cultural crossroads of Europe and Asia.',
    history: 'According to legend, King Vakhtang Gorgasali founded the city in the 5th century CE after his falcon fell into a hot sulfur spring. Due to its position, it was fought over and rebuilt dozens of times by Persians, Arabs, Mongols, and Russians.',
    cuisine: 'Georgian cuisine is a unique fusion of Mediterranean and Asian flavors. Enjoy Khachapuri (cheese-filled bread topped with an egg), Khinkali (spicy soup dumplings), and rich walnut-paste dips.',
    culture_craft: 'Georgia is the cradle of wine-making, fermenting grape juice in clay vessels called qvevri for 8,000 years. The city has a thriving art and theater scene, centered around the marionette theater of Rezo Gabriadze.',
    architecture: 'The old town features narrow streets lined with 19th-century houses with carved wooden balconies. The sulfur bath district, Abanotubani, features brick domes built over natural hot springs.',
    hidden_gem: 'The hidden courtyard of the London Hotel, a crumbling, historic 19th-century building with faded ceiling frescoes.',
    amazing_facts: [
      'Georgia has an 8,000-year-old continuous wine-making history, the oldest in the world.',
      'The city\'s name comes from the Old Georgian word "Tbili", which means warm, referring to the hot springs.',
      'Narikala Fortress, overlooking the city, was established in the 4th century, older than the city itself.'
    ],
    emotional_vibe: 'Grapevine paths climb old brick walls. In the sulfur bath dome, steam rises, carrying the whispers of centuries of travelers.'
  },
  {
    id: 'oaxaca',
    name: 'Oaxaca',
    nameHindi: 'ओहाका',
    country: 'Mexico',
    type: 'global',
    tagline: 'The kitchen and color heart of Mexico',
    travelerType: 'For the Culture & Spice Seeker',
    imageUrl: '/images/safar/oaxaca.png',
    bestTime: 'October to May',
    why_visit: 'Oaxaca is a vibrant valley city rich in indigenous Zapotec and Mixtec culture, colonial architecture, and the most famous culinary traditions in Mexico.',
    history: 'A major center of Zapotec civilization for over 1,500 years at Monte Albán, the region was conquered by the Aztecs and later the Spanish, creating a rich syncretism that defines its festivals, crafts, and food.',
    cuisine: 'Oaxaca is the "Land of the Seven Moles" - complex sauces made from dozens of ingredients including chilies, seeds, and chocolate. Enjoy tlayudas, tamales wrapped in banana leaves, and artisanal mezcal.',
    culture_craft: 'The surrounding villages specialize in unique crafts: black pottery (barro negro) in Coyotepec, hand-woven wool rugs in Teotitlán, and brightly painted wooden animal figures called alebrijes.',
    architecture: 'The historic center is built from green volcanic stone (cantera), featuring grand churches like Santo Domingo de Guzmán with its ornate, gold-leaf covered interior.',
    hidden_gem: 'Hierve el Agua, a set of natural rock formations that resemble petrified waterfalls, set on the edge of a deep mountain valley.',
    amazing_facts: [
      'Monte Albán was founded in 500 BCE, making it one of the earliest cities in Mesoamerica.',
      'The Tule Tree near Oaxaca has the stoutest trunk of any tree in the world, with a diameter of over 14 meters.',
      'The Day of the Dead (Día de los Muertos) celebrations in Oaxaca are among the most colorful and elaborate in the world.'
    ],
    emotional_vibe: 'Marigold petals carpet the stone streets. The scent of hot chocolate and wood smoke fills the evening market.'
  },
  {
    id: 'zanzibar',
    name: 'Zanzibar',
    nameHindi: 'ज़ंज़ीबार',
    country: 'Tanzania',
    type: 'global',
    tagline: 'The spice island of the Indian Ocean',
    travelerType: 'For the Spice & Sea Traveler',
    imageUrl: '/images/safar/zanzibar.png',
    bestTime: 'June to October',
    why_visit: 'Zanzibar is a tropical archipelago off the coast of East Africa. Its historic capital, Stone Town, is a beautiful maze of coral-stone buildings, spice markets, and white sand beaches washed by the turquoise Indian Ocean.',
    history: 'A former colony of Oman, Zanzibar was the center of the spice and slave trade in East Africa. It was ruled by Arab sultans, Portuguese sailors, and British governors, creating a unique Swahili culture.',
    cuisine: 'The food is a delicious blend of African, Arab, and Indian flavors. Try Zanzibari Biryani, coconut crab soup, and street food like Urojo (spicy mango broth filled with potato balls).',
    culture_craft: 'The island is famous for its hand-carved teak doors, spice cultivation (cloves, nutmeg, cinnamon), and traditional dhow sailing boat construction.',
    architecture: 'Stone Town is built from coralline rock, featuring narrow streets, overhanging balconies, and grand palaces like the House of Wonders, featuring Arab and Swahili influences.',
    hidden_gem: 'The Jozani Forest, a quiet sanctuary that is home to the rare Zanzibar Red Colobus Monkey, found nowhere else in the world.',
    amazing_facts: [
      'Zanzibar was once the world\'s largest producer of cloves.',
      'Freddie Mercury, the lead singer of the rock band Queen, was born in Stone Town in 1946.',
      'The Anglo-Zanzibar War of 1896 lasted only 38 minutes, making it the shortest war in recorded history.'
    ],
    emotional_vibe: 'White sails catch the evening wind on the horizon. The smell of clove blossoms drifts through the old stone streets.'
  },
  {
    id: 'porto',
    name: 'Porto',
    nameHindi: 'पोर्टो',
    country: 'Portugal',
    type: 'global',
    tagline: 'The granite city on the Douro',
    travelerType: 'For the Riverside Dreamer',
    imageUrl: '/images/safar/porto.png',
    bestTime: 'May to September',
    why_visit: 'Porto is a historic merchant city built along the steep banks of the Douro River. Famous for its port wine cellars, iron bridges, and blue-tiled churches, it has a rugged, creative charm.',
    history: 'Porto dates back to the Roman period as Portus Cale. It grew wealthy as a ship-building port during the Age of Discovery and developed a monopoly on the port wine trade with England in the 17th century.',
    cuisine: 'Try the Francesinha (a rich sandwich of meats covered in melted cheese and hot tomato-beer sauce), fresh octopus, and local Port wine at the cellars of Vila Nova de Gaia.',
    culture_craft: 'The city is known for its traditional filigree jewelry, cork products, and hand-painted azulejo tiles that cover the walls of train stations and churches.',
    architecture: 'The architecture features granite buildings, narrow alleys, and six grand bridges designed by students of Gustave Eiffel. The São Bento station features 20,000 tiles depicting historical battles.',
    hidden_gem: 'The Jardim do Morro at sunset, a green park on a hill across the river offering panoramic views of the old city reflecting in the water.',
    amazing_facts: [
      'The city\'s residents are nicknamed "tripeiros" (tripe eaters) because they gave all their meat to sailors in the 15th century, keeping only tripe.',
      'Livraria Lello, a beautiful Art Nouveau bookstore in Porto, is rumored to have inspired the library of Hogwarts in Harry Potter.',
      'Porto\'s historical center was declared a UNESCO World Heritage site in 1996.'
    ],
    emotional_vibe: 'Fog rolls in from the Atlantic, blanketing the iron bridge. The river carries the red glow of sunset.'
  },
  {
    id: 'luang-prabang',
    name: 'Luang Prabang',
    nameHindi: 'लुआंग प्रबांग',
    country: 'Laos',
    type: 'global',
    tagline: 'The quiet fusion of traditions on the Mekong',
    travelerType: 'For the Devoted Pilgrim',
    imageUrl: '/images/safar/luang-prabang.png',
    bestTime: 'November to February',
    why_visit: 'Luang Prabang is a peaceful town set at the confluence of the Nam Khan and Mekong rivers. With its golden monasteries, French colonial villas, and quiet street life, it is a sanctuary of Buddhist devotion.',
    history: 'The ancient capital of the Lan Xang (Million Elephants) kingdom, the town was the center of Laotian royalty and religion. It became a French protectorate in 1893, leading to its unique architectural blend.',
    cuisine: 'Try local specialties like Luang Prabang salad, Or Lam (spicy wood-flavored stew), sticky rice, and Jeow Bong (sweet and spicy chili paste made with buffalo skin).',
    culture_craft: 'The town is famous for hand-woven silk, mulberry paper crafts, and the daily morning alms-giving ceremony (Sai Bat) where hundreds of monks walk through the streets in silence.',
    architecture: 'The architecture features traditional Laotian wooden monasteries with sweeping, low-hung roofs (like Wat Xieng Thong) built next to brick French administrative colonial buildings.',
    hidden_gem: 'The Kuang Si Falls, a spectacular multi-tiered waterfall of turquoise water cascading through the jungle south of the town.',
    amazing_facts: [
      'The entire town was designated a UNESCO World Heritage site in 1995 to preserve its architectural blend.',
      'Wat Xieng Thong contains a spectacular "tree of life" glass mosaic on its rear wall, created in 1960.',
      'The town has a strict curfew where all shops and restaurants close by 11:30 PM to preserve the quiet.'
    ],
    emotional_vibe: 'Monks walk in orange silence as the mist rises from the Mekong. The world moves slowly here, as if holding its breath.'
  },
  {
    id: 'salzburg',
    name: 'Salzburg',
    nameHindi: 'सॉल्ज़बर्ग',
    country: 'Austria',
    type: 'global',
    tagline: 'The city of sound and salt',
    travelerType: 'For the Classic Music Lover',
    imageUrl: '/images/safar/salzburg.png',
    bestTime: 'September to October or May to June',
    why_visit: 'Salzburg is a stunning baroque city set against the backdrop of the Alps. The birthplace of Mozart, it offers world-class classical music, grand fortresses, and pristine alpine nature.',
    history: 'Salzburg grew wealthy from the salt mines of the surrounding hills. It was ruled for centuries by powerful Prince-Archbishops who transformed the city into the "Rome of the North" with grand baroque churches.',
    cuisine: 'Indulge in Salzburger Nockerl (a sweet, fluffy baked soufflé representing the snow-covered peaks), Wiener Schnitzel, and Mozartkugel (pistachio marzipan chocolates).',
    culture_craft: 'The city is synonymous with classical music. It hosts the annual Salzburg Festival, one of the most prestigious opera and classical music festivals in the world.',
    architecture: 'The historic center is a masterpiece of baroque architecture, dominated by the Hohensalzburg Fortress, one of the largest medieval castles in Europe, sitting on a cliff over the Salzach River.',
    hidden_gem: 'The Petersfriedhof (St. Peter\'s Cemetery), a beautiful, quiet cemetery carved into the rock face of the Festungsberg hill.',
    amazing_facts: [
      'Wolfgang Amadeus Mozart was born in Salzburg in 1756, and his family home is preserved as a museum.',
      'Salzburg\'s name literally means "Salt Castle", referring to the barges that carried salt down the river.',
      'The city served as the primary filming location for the classic 1965 musical film The Sound of Music.'
    ],
    emotional_vibe: 'Domes of green copper stand against grey mountain peaks. The sound of a violin drifts over the bridge.'
  },
  {
    id: 'petra',
    name: 'Petra',
    nameHindi: 'पेत्रा',
    country: 'Jordan',
    type: 'global',
    tagline: 'The rose-red city half as old as time',
    travelerType: 'For the Canyon Explorer',
    imageUrl: '/images/safar/petra.png',
    bestTime: 'March to May or September to November',
    why_visit: 'Petra is an ancient, ruined city carved directly into the red sandstone cliffs of Jordan\'s desert canyons. It is one of the world\'s most spectacular archaeological wonders, accessed through a narrow, winding gorge.',
    history: 'Established in the 4th century BCE as the capital of the Nabataean Kingdom, Petra grew rich as a hub for spice and incense trade. It featured sophisticated water systems before falling to Rome and being abandoned after earthquakes.',
    cuisine: 'Savor Mansaf (Jordan\'s national dish of lamb cooked in fermented dried yogurt sauce served over rice), grilled kebabs, and sweet baklava, accompanied by cardamon-flavored Bedouin coffee.',
    culture_craft: 'The local Bedouin tribes maintain their traditions of hospitality, camel herding, and weaving. Sand art in glass bottles using colored desert sands is a popular local craft.',
    architecture: 'The monuments are carved directly into the cliff faces, showing a unique blend of Hellenistic, Egyptian, and Nabataean styles. The Treasury (Al-Khazneh) features an iconic carved facade.',
    hidden_gem: 'The Monastery (Ad-Deir), a spectacular carved facade larger than the Treasury, located at the end of an 800-step climb up a desert canyon.',
    amazing_facts: [
      'Petra was carved from the top down, with builders cutting steps into the rock to carve the facades from the roof down.',
      'Only about 15% of the ancient city has been excavated; the remaining 85% remains buried underground.',
      'The city is accessed through the Siq, a narrow natural gorge over a kilometer long, flanked by 80-meter-high cliffs.'
    ],
    emotional_vibe: 'Sunlight filters through a crack in the red rock. A monumental facade rises from the sand like a desert temple.'
  },
  {
    id: 'dubrovnik',
    name: 'Dubrovnik',
    nameHindi: 'डुब्रोवनिक',
    country: 'Croatia',
    type: 'global',
    tagline: 'The stone stronghold on the Adriatic',
    travelerType: 'For the Coastal Historian',
    imageUrl: '/images/safar/dubrovnik.png',
    bestTime: 'May to June or September to October',
    why_visit: 'Dubrovnik is a stunning walled city on the Adriatic Sea. Its massive stone walls, orange-tiled roofs, and clean limestone streets set against the blue sea make it the "Pearl of the Adriatic."',
    history: 'Founded in the 7th century, Dubrovnik (historically Ragusa) was a powerful maritime republic that competed with Venice. It preserved its independence through diplomacy and massive fortifications that were never breached.',
    cuisine: 'Enjoy Dalmatian seafood dishes, including black risotto (cooked with cuttlefish ink), grilled octopus, and fresh oysters from nearby Ston, paired with local Croatian white wines.',
    culture_craft: 'The city is known for traditional gold filigree jewelry and silk embroidery. The summer festival features open-air theater performances on the fortress terraces.',
    architecture: 'The old town is surrounded by two kilometers of stone walls up to six meters thick. Inside, the architecture is a mix of Gothic, Renaissance, and Baroque palaces and monasteries.',
    hidden_gem: 'The Buža Bar, a small café clinging to the cliffs outside the city walls, accessible through a hole in the stone wall, offering sunset swimming access.',
    amazing_facts: [
      'Dubrovnik\'s quarantine system, established in 1377 to prevent the plague, was the first of its kind in the world.',
      'The city abolished the slave trade in 1416, centuries before most of Europe.',
      'The massive walls of the old town served as the primary filming location for King\'s Landing in Game of Thrones.'
    ],
    emotional_vibe: 'White stone walls meet the blue Adriatic. The sun sets, painting the terracotta roofs in shades of gold.'
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    nameHindi: 'कार्टाजेना',
    country: 'Colombia',
    type: 'global',
    tagline: 'The walled jewel of the Caribbean',
    travelerType: 'For the Colorful Fort Stroller',
    imageUrl: '/images/safar/cartagena.png',
    bestTime: 'December to April',
    why_visit: 'Cartagena de Indias is a colonial city on Colombia\'s Caribbean coast. Its walled old city is a colorful array of 18th-century houses, flowered balconies, and grand Spanish stone fortifications.',
    history: 'Founded in 1533 by Pedro de Heredia, Cartagena was the primary port from which Spanish gold was shipped back to Europe. This wealth made it a prime target for pirates, leading to the construction of South America\'s largest defensive walls.',
    cuisine: 'The food is a tropical Caribbean-Colombian fusion. Enjoy ceviche, coconut rice, fried plantains (patacones), and fresh tropical fruits like arequipe and lulo.',
    culture_craft: 'The city is home to Palenquera women wearing colorful traditional dresses, selling fruit from baskets on their heads. Local crafts include emerald jewelry and woven Wayuu bags.',
    architecture: 'The architecture is colorful Spanish colonial. Mansions are painted in bright yellows, blues, and corals, featuring large wooden balconies overflowing with bougainvillea.',
    hidden_gem: 'The Getsemaní neighborhood, a historically working-class area just outside the walls, famous for its street art, colorful umbrellas, and lively community plazas.',
    amazing_facts: [
      'The San Felipe de Barajas Castle is the most formidable fortress the Spanish ever built in their colonies.',
      'The city\'s historic walls took over 200 years to complete, constructed from coral stone.',
      'Cartagena was a major setting for the novels of Gabriel García Márquez, including Love in the Time of Cholera.'
    ],
    emotional_vibe: 'Salsa music drifts from a colorful courtyard. The warm Caribbean breeze rolls over the ancient stone battlements.'
  },
  {
    id: 'luang-namtha',
    name: 'Luang Namtha',
    nameHindi: 'लुआंग नामथा',
    country: 'Laos',
    type: 'global',
    tagline: 'The borderlands of forest and hill tribes',
    travelerType: 'For the Eco Trekker',
    imageUrl: '/images/safar/luang-namtha.png',
    bestTime: 'November to February',
    why_visit: 'Luang Namtha, located in northern Laos near the Chinese border, is the country\'s premier ecotourism destination, offering rugged treks through the Nam Ha National Protected Area and encounters with diverse hill tribes.',
    history: 'A remote frontier region, the valley was a major battlefield during the Indochina wars. Today it is a quiet center of agricultural communities and sustainable tourism projects managed by local ethnic minorities.',
    cuisine: 'Try local upland dishes like Lap (herbal minced meat salad), forest mushrooms, bamboo shoot stews, and roasted river fish, served with purple sticky rice.',
    culture_craft: 'The region is home to over twenty ethnic groups, including the Akha, Lanten, and Hmong. Each group preserves its distinct weaving, indigo dyeing, and silverwork traditions.',
    architecture: 'The towns feature simple wooden and bamboo homes built on stilts. Villages have traditional communal houses where tribal elders meet to settle community disputes.',
    hidden_gem: 'The Nam Dee Waterfall, a quiet fall located near a Lanten village, offering peaceful pools and paths through the bamboo forest.',
    amazing_facts: [
      'The Nam Ha National Protected Area is one of the last habitats for wild Asian elephants and clouded leopards in northern Laos.',
      'The Lanten people are known for making handmade paper from bamboo, using it for religious scripts.',
      'Eco-tourism projects here have won international awards for directly funding community forest conservation.'
    ],
    emotional_vibe: 'Forest paths wind through giant bamboo stands. The evening mist settles over green valleys of rice.'
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    nameHindi: 'मराकेश',
    country: 'Morocco',
    type: 'global',
    tagline: 'The red city under the Atlas peaks',
    travelerType: 'For the Sensory Explorer',
    imageUrl: '/images/safar/marrakech.png',
    bestTime: 'March to May or September to November',
    why_visit: 'Marrakech is a historic imperial city under the snow-clad peaks of the Atlas Mountains. Its bustling square Jemaa el-Fna, vibrant souks, and hidden riad gardens offer an intense sensory experience.',
    history: 'Founded in 1070 CE by the Almoravid dynasty, Marrakech became the capital of an empire that stretched from Spain to Senegal. It gave its name to the country itself (Morocco, derived from Marrakech).',
    cuisine: 'Indulge in Tanjia Marrakchia (lamb slow-cooked with spices in a clay jar in public bath ovens), couscous, tagines, and sweets flavored with orange blossom water.',
    culture_craft: 'The souks are filled with craftsmen working in metal, leather, wood, and textiles. The city is also famous for its traditional herbalists and perfume makers.',
    architecture: 'The buildings are constructed from red clay, giving the city its nickname "The Red City." The Koutoubia Mosque features a spectacular 12th-century minaret, a model for the Giralda in Seville.',
    hidden_gem: 'The Le Jardin Secret, a beautifully restored historic palace garden in the heart of the medina, showcasing traditional Islamic layout.',
    amazing_facts: [
      'Jemaa el-Fna square is a UNESCO Masterpiece of the Oral Heritage of Humanity, hosting snake charmers, storytellers, and musicians.',
      'The Majorelle Garden, restored by fashion designer Yves Saint Laurent, features cobalt blue villa walls surrounded by exotic cacti.',
      'The city walls, built from red earth in the 12th century, stretch for over 19 kilometers.'
    ],
    emotional_vibe: 'Devotional chants rise as the sun sets over the red roofs. The air smells of cumin, mint, and orange blossoms.'
  },
  {
    id: 'ushuaia',
    name: 'Ushuaia',
    nameHindi: 'उशुआइया',
    country: 'Argentina',
    type: 'global',
    tagline: 'The end of the earth',
    travelerType: 'For the Antarctic Voyager',
    imageUrl: '/images/safar/ushuaia.png',
    bestTime: 'December to March',
    why_visit: 'Ushuaia, the southernmost city in the world, sits on the Beagle Channel in Tierra del Fuego. Backed by the Martial Glacier, it is the primary gateway for expeditions to Antarctica and a sanctuary of subantarctic wilderness.',
    history: 'Originally inhabited by the Yaghan canoe people, the area was settled by British missionaries. Argentina established a high-security penal colony here in the late 19th century, with prisoners building the city\'s infrastructure.',
    cuisine: 'Enjoy fresh Centolla (King Crab), Patagonian sea bass, and roasted lamb, accompanied by local craft beers brewed with pure glacier water.',
    culture_craft: 'The city preserves maritime history and tales of early polar explorers. Local artisans craft goods from guanaco wool and native lenga wood.',
    architecture: 'The houses feature colorful sheet-metal walls and steep, gabled roofs designed to slide off heavy winter snows, set against the dark waters of the channel.',
    hidden_gem: 'The Bahia Lapataia in Tierra del Fuego National Park, a quiet fjord marking the absolute end of the Pan-American Highway.',
    amazing_facts: [
      'Ushuaia is the closest port in the world to Antarctica, located only 1,000 kilometers from the Antarctic Peninsula.',
      'The "Train of the End of the World" was originally built by prisoners to haul wood from the forest to the town.',
      'In winter, the city receives only about six hours of daylight, while in summer it gets nearly eighteen.'
    ],
    emotional_vibe: 'Dark mountains slide into a grey sea. The wind blows cold from the South Pole, carrying the promise of ice.'
  }
];
