export interface KathakarEntry {
  dayIndex: number;
  story_title: string;
  story_title_hi?: string;
  origin: string;
  origin_hi?: string;
  tradition: 'indian' | 'global';
  estimated_read: string;
  the_story: string;
  what_this_story_knows: string;
  emotional_core: string;
}

export const KATHAKAR_ENTRIES: KathakarEntry[] = [
  {
    dayIndex: 1,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 2,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 3,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 4,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 5,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 6,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 7,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 8,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 9,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 10,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 11,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 12,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 13,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 14,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 15,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 16,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 17,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 18,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 19,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 20,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 21,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 22,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 23,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 24,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 25,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 26,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 27,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 28,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 29,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 30,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 31,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 32,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 33,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 34,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 35,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 36,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 37,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 38,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 39,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 40,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 41,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 42,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 43,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 44,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 45,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 46,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 47,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 48,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 49,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 50,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 51,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 52,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 53,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 54,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 55,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 56,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 57,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 58,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 59,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 60,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 61,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 62,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 63,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 64,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 65,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 66,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 67,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 68,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 69,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 70,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 71,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 72,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 73,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 74,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 75,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 76,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 77,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 78,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 79,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 80,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 81,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 82,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 83,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 84,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 85,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 86,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 87,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 88,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  },
  {
    dayIndex: 89,
    story_title: "The Empty Cup",
    story_title_hi: "खाली प्याला",
    origin: "Zen Tradition",
    origin_hi: "ज़ेन परंपरा",
    tradition: "global",
    estimated_read: "3 min",
    the_story: "A scholar went to visit a famous Zen master to ask about Zen. As the master spoke, the scholar constantly interrupted with his own opinions and learnings. The master listened quietly and offered him tea.\n\nHe poured the tea until the cup was full, and then kept pouring. The tea overflowed, spilling onto the table and the floor. 'Stop pouring!' said the scholar. 'It is full. No more will go in.' 'Like this cup,' said the master, 'you are full of your own opinions. How can I show you Zen unless you first empty your cup?'",
    what_this_story_knows: "To receive new insights, we must first suspend our existing assumptions and create space in our minds.",
    emotional_core: "Humility is the opening of the door to learning."
  },
  {
    dayIndex: 90,
    story_title: "The Golden Swan",
    story_title_hi: "स्वर्ण हंस",
    origin: "Jataka Tales",
    origin_hi: "जातक कथाएं",
    tradition: "indian",
    estimated_read: "4 min",
    the_story: "There was a poor widow with two daughters who struggled to survive. A swan with golden feathers saw their plight and decided to help them. Every day, the swan flew to their cottage and dropped a single golden feather, which the family sold to buy food.\n\nOver time, the widow grew greedy. She feared the swan would fly away and never return. One day, she trapped the swan and plucked all its feathers. Instantly, the golden feathers turned into ordinary white ones. The swan flew away, leaving the widow to realize that greed destroys the very source of abundance.",
    what_this_story_knows: "Impatience and greed destroy the natural, gradual flow of support and abundance in our lives.",
    emotional_core: "Trust the rhythm of what is given."
  }
];
