export interface CosmicEntry {
  dayIndex: number;
  id: string;
  name: string;
  nameHindi: string;
  imageUrl: string;
  category: string;
  intro: string;
  deepDive: string;
  scale: string;
  discovery: string;
  mindBend: string;
}

export const COSMIC_ENTRIES: CosmicEntry[] = [
  {
    dayIndex: 1,
    id: "pillars_0",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 2,
    id: "blackhole_1",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 3,
    id: "pillars_2",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 4,
    id: "blackhole_3",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 5,
    id: "pillars_4",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 6,
    id: "blackhole_5",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 7,
    id: "pillars_6",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 8,
    id: "blackhole_7",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 9,
    id: "pillars_8",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 10,
    id: "blackhole_9",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 11,
    id: "pillars_10",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 12,
    id: "blackhole_11",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 13,
    id: "pillars_12",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 14,
    id: "blackhole_13",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 15,
    id: "pillars_14",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 16,
    id: "blackhole_15",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 17,
    id: "pillars_16",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 18,
    id: "blackhole_17",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 19,
    id: "pillars_18",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 20,
    id: "blackhole_19",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 21,
    id: "pillars_20",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 22,
    id: "blackhole_21",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 23,
    id: "pillars_22",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 24,
    id: "blackhole_23",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 25,
    id: "pillars_24",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 26,
    id: "blackhole_25",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 27,
    id: "pillars_26",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 28,
    id: "blackhole_27",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 29,
    id: "pillars_28",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 30,
    id: "blackhole_29",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 31,
    id: "pillars_30",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 32,
    id: "blackhole_31",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 33,
    id: "pillars_32",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 34,
    id: "blackhole_33",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 35,
    id: "pillars_34",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 36,
    id: "blackhole_35",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 37,
    id: "pillars_36",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 38,
    id: "blackhole_37",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 39,
    id: "pillars_38",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 40,
    id: "blackhole_39",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 41,
    id: "pillars_40",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 42,
    id: "blackhole_41",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 43,
    id: "pillars_42",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 44,
    id: "blackhole_43",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 45,
    id: "pillars_44",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 46,
    id: "blackhole_45",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 47,
    id: "pillars_46",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 48,
    id: "blackhole_47",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 49,
    id: "pillars_48",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 50,
    id: "blackhole_49",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 51,
    id: "pillars_50",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 52,
    id: "blackhole_51",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 53,
    id: "pillars_52",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 54,
    id: "blackhole_53",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 55,
    id: "pillars_54",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 56,
    id: "blackhole_55",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 57,
    id: "pillars_56",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 58,
    id: "blackhole_57",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  },
  {
    dayIndex: 59,
    id: "pillars_58",
    name: "The Pillars of Creation",
    nameHindi: "सृष्टि के स्तंभ",
    imageUrl: "/images/cosmos/pillars.png",
    category: "Stellar Nursery",
    intro: "In the Eagle Nebula, columns of interstellar gas and dust tower seven light-years tall, forging new stars this very moment.",
    deepDive: "The Pillars of Creation are located within the Eagle Nebula, approximately 6,500 light-years from Earth. They are composed of dense molecular hydrogen and dust, which collapse under gravity to form new stars. The ultraviolet light from nearby hot stars is slowly evaporating the pillars, forming finger-like structures that contain protostars at their tips.\n\nAstronomers suggest the pillars may have already been destroyed by a supernova thousands of years ago, but their light is still traveling toward us, showing a window into the deep past.",
    scale: "The tallest pillar is about 7 light-years tall, or 41 trillion miles.",
    discovery: "Imaged by the Hubble Space Telescope in 1995, revealing stars emerging from dust.",
    mindBend: "We see the pillars as they existed 6,500 years ago, demonstrating that astronomy is time travel."
  },
  {
    dayIndex: 60,
    id: "blackhole_59",
    name: "Supermassive Black Holes",
    nameHindi: "कृष्ण विवर",
    imageUrl: "/images/cosmos/blackhole.png",
    category: "Spacetime Phenomenon",
    intro: "A region of spacetime where gravity is so extreme that not even light can escape its event horizon.",
    deepDive: "At the center of most galaxies, including our own Milky Way, lies a supermassive black hole. Sagittarius A*, our central black hole, contains the mass of four million suns compressed into a tiny volume. The gravity is so strong that space and time swap roles inside the horizon, making the singularity inevitable.\n\nIn 2019, the Event Horizon Telescope captured the first image of a black hole in galaxy M87, proving Einstein's General Relativity in extreme fields.",
    scale: "Sagittarius A* has an event horizon of 12 million kilometers across.",
    discovery: "Derived by Karl Schwarzschild in 1916 while serving in World War I.",
    mindBend: "Inside the event horizon, the singularity is in your future. You cannot avoid it, just as you cannot avoid tomorrow."
  }
];
