export interface DuniyaEntry {
  summary: string;
  dayIndex: number;
  type: 'situation' | 'system';
  title: string;
  title_hi?: string;
  region: string;
  region_hi?: string;
  situation?: string;
  why_it_matters?: string;
  one_thing_to_understand?: string;
  what_it_is?: string;
  how_it_works?: string;
  who_benefits?: string;
  limits?: string;
  india_angle?: string;
  question?: string;
}

export const DUNIYA_ENTRIES: DuniyaEntry[] = [
  {
    dayIndex: 1,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 2,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 3,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 4,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 5,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 6,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 7,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 8,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 9,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 10,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 11,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 12,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 13,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 14,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 15,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 16,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 17,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 18,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 19,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 20,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 21,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 22,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 23,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 24,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 25,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 26,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 27,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 28,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 29,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 30,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 31,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 32,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 33,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 34,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 35,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 36,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 37,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 38,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 39,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 40,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 41,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 42,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 43,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 44,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 45,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 46,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 47,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 48,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 49,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 50,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 51,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 52,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 53,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 54,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 55,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 56,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 57,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 58,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 59,
    summary: `Explore Bhutan's unique governance philosophy that rejects GDP in favor of Gross National Happiness. By prioritizing spiritual wellbeing, cultural preservation, and environmental conservation, this Himalayan kingdom asks a vital question: what would our lives look like if we stopped measuring only productivity?`,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 60,
    summary: `A look at the massive global challenge of marine plastic pollution and the innovative, passive technologies designed to clean our oceans. This situation highlights how understanding natural currents can help us undo our ecological damage, urging us to act before it is too late.`,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  }
];
