export interface DuniyaEntry {
  dayIndex: number;
  type: 'situation' | 'system';
  title: string;
  title_hi?: string;
  region: string;
  region_hi?: string;
  situation?: string;
  why_it_matters?: string;
  one_thing_to_understand?: string;
  what_it_is?: string;
  how_it_works?: string;
  who_benefits?: string;
  limits?: string;
  india_angle?: string;
  question?: string;
}

export const DUNIYA_ENTRIES: DuniyaEntry[] = [
  {
    dayIndex: 1,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 2,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 3,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 4,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 5,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 6,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 7,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 8,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 9,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 10,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 11,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 12,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 13,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 14,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 15,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 16,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 17,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 18,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 19,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 20,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 21,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 22,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 23,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 24,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 25,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 26,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 27,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 28,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 29,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 30,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 31,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 32,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 33,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 34,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 35,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 36,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 37,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 38,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 39,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 40,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 41,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 42,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 43,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 44,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 45,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 46,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 47,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 48,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 49,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 50,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 51,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 52,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 53,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 54,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 55,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 56,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 57,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 58,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  },
  {
    dayIndex: 59,
    type: "system",
    title: "Gross National Happiness in Bhutan",
    title_hi: "भूटान में सकल राष्ट्रीय प्रसन्नता",
    region: "South Asia · Bhutan",
    region_hi: "दक्षिण एशिया · भूटान",
    situation: "",
    why_it_matters: "",
    one_thing_to_understand: "",
    what_it_is: "A governance philosophy that prioritizes collective wellbeing and environmental protection over material consumption.",
    how_it_works: "Policies are evaluated by a GNH Commission using survey metrics across nine domains, including psychological wellbeing and ecological diversity.",
    who_benefits: "The general population, through preserved forests, strong cultural identity, and subsidized healthcare.",
    limits: "Economic inequality and historical marginalization of certain ethnic groups are sometimes overlooked by GNH rhetoric.",
    india_angle: "India is Bhutan's largest trade partner and has supported its hydropower development while studying GNH frameworks.",
    question: "What metrics would your own life optimize for if you stopped measuring productivity?"
  },
  {
    dayIndex: 60,
    type: "situation",
    title: "The Ocean Cleanup Campaign",
    title_hi: "महासागर सफाई अभियान",
    region: "Global Oceans",
    region_hi: "वैश्विक महासागर",
    situation: "Over 150 million tons of plastic circulate in our oceans, threatening marine lifecycles and human food security through microplastics.",
    why_it_matters: "Plastic takes hundreds of years to degrade, breaking into toxic particles that absorb organic pollutants and enter the marine food web.",
    one_thing_to_understand: "Passive systems utilizing ocean currents can collect plastic far more efficiently than active ships with nets.",
    what_it_is: "",
    how_it_works: "",
    who_benefits: "",
    limits: "",
    india_angle: "",
    question: ""
  }
];
