// src/app/(app)/riyaz/songs-pool.ts
import { RiyazSong } from './data';

export const HINDI_SONGS: RiyazSong[] = [
  { era: 'contemporary', language: 'hindi', song_title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali, Mohit Chauhan', film_or_album: 'Rockstar', year: '2011', youtube_id: 'T94PHkuyd8c' },
  { era: 'contemporary', language: 'hindi', song_title: 'Dil Se Re', artist: 'A.R. Rahman, Anuradha Sriram', film_or_album: 'Dil Se', year: '1998', youtube_id: 'Y7yqJ9vG4qU' },
  { era: 'contemporary', language: 'hindi', song_title: 'Tum Hi Ho', artist: 'Arijit Singh', film_or_album: 'Aashiqui 2', year: '2013', youtube_id: 'Umqb9KENgmk' },
  { era: 'contemporary', language: 'hindi', song_title: 'Kabira', artist: 'Tochi Raina, Rekha Bhardwaj', film_or_album: 'Yeh Jawaani Hai Deewani', year: '2013', youtube_id: 'jHNNMj5bNQw' },
  { era: 'contemporary', language: 'hindi', song_title: 'Chaiyya Chaiyya', artist: 'Sukhwinder Singh, Sapna Awasthi', film_or_album: 'Dil Se', year: '1998', youtube_id: 'YOYN9qNXmAw' },
  { era: 'contemporary', language: 'hindi', song_title: 'Kal Ho Naa Ho', artist: 'Sonu Nigam', film_or_album: 'Kal Ho Naa Ho', year: '2003', youtube_id: 'g0eO74UmRBs' },
  { era: 'contemporary', language: 'hindi', song_title: 'Kesariya', artist: 'Arijit Singh', film_or_album: 'Brahmastra', year: '2022', youtube_id: 'BddP6PYo2Gs' },
  { era: 'classical', language: 'hindi', song_title: 'Lag Ja Gale', artist: 'Lata Mangeshkar', film_or_album: 'Woh Kaun Thi?', year: '1964', youtube_id: 'TFr6G5zveS8' },
  { era: 'classical', language: 'hindi', song_title: 'Tu Hi Re', artist: 'Hariharan, Kavita Krishnamurthy', film_or_album: 'Bombay', year: '1995', youtube_id: '5YVw74nZ334' },
  { era: 'classical', language: 'hindi', song_title: 'Kabhi Kabhie Mere Dil Mein', artist: 'Mukesh, Lata Mangeshkar', film_or_album: 'Kabhi Kabhie', year: '1976', youtube_id: 's7H_b_f2K4w' },
  { era: 'contemporary', language: 'hindi', song_title: 'Yun Hi Chala Chal', artist: 'Kailash Kher, Udit Narayan, Hariharan', film_or_album: 'Swades', year: '2004', youtube_id: 'tN68f_Tev4Q' },
  { era: 'contemporary', language: 'hindi', song_title: 'Yeh Jo Des Hai Tera', artist: 'A.R. Rahman', film_or_album: 'Swades', year: '2004', youtube_id: 'wVGs4v2r2Jc' },
  { era: 'contemporary', language: 'hindi', song_title: 'Lukka Chuppi', artist: 'Lata Mangeshkar, A.R. Rahman', film_or_album: 'Rang De Basanti', year: '2006', youtube_id: '_ikZtcgARxo' },
  { era: 'contemporary', language: 'hindi', song_title: 'Mitwa', artist: 'Shafqat Amanat Ali, Shankar-Ehsaan-Loy', film_or_album: 'Kabhi Alvida Naa Kehna', year: '2006', youtube_id: '0S43a8T9dpc' },
  { era: 'contemporary', language: 'hindi', song_title: 'Agar Tum Saath Ho', artist: 'Alka Yagnik, Arijit Singh', film_or_album: 'Tamasha', year: '2015', youtube_id: 'sK7riqg2mr4' },
  { era: 'contemporary', language: 'hindi', song_title: 'Channa Mereya', artist: 'Arijit Singh', film_or_album: 'Ae Dil Hai Mushkil', year: '2016', youtube_id: '284Ov7ysyfA' },
  { era: 'contemporary', language: 'hindi', song_title: 'Pee Loon', artist: 'Mohit Chauhan', film_or_album: 'Once Upon A Time In Mumbaai', year: '2010', youtube_id: '5ySshT9zF3E' },
  { era: 'contemporary', language: 'hindi', song_title: 'Zehnaseeb', artist: 'Chinmayi Sripaada, Shekhar Ravjiani', film_or_album: 'Hasee Toh Phasee', year: '2014', youtube_id: '0i4S_NgaDQA' },
  { era: 'contemporary', language: 'hindi', song_title: 'Bulleya', artist: 'Amit Mishra, Shilpa Rao', film_or_album: 'Ae Dil Hai Mushkil', year: '2016', youtube_id: 'hXh35C2eLO4' },
  { era: 'contemporary', language: 'hindi', song_title: 'Ae Dil Hai Mushkil', artist: 'Arijit Singh', film_or_album: 'Ae Dil Hai Mushkil', year: '2016', youtube_id: '6FURuLySyoU' },
  { era: 'contemporary', language: 'hindi', song_title: 'Phir Se Ud Chala', artist: 'Mohit Chauhan', film_or_album: 'Rockstar', year: '2011', youtube_id: '2g21_w38Z40' },
  { era: 'contemporary', language: 'hindi', song_title: 'Nadaan Parindey', artist: 'A.R. Rahman, Mohit Chauhan', film_or_album: 'Rockstar', year: '2011', youtube_id: 'vUCM_O284w0' },
  { era: 'classical', language: 'hindi', song_title: 'Aaj Kal Tere Mere Pyar Ke Charche', artist: 'Mohammed Rafi, Suman Kalyanpur', film_or_album: 'Brahmachari', year: '1968', youtube_id: 'm86x-Cqj07Y' },
  { era: 'classical', language: 'hindi', song_title: 'Chaudhvin Ka Chand Ho', artist: 'Mohammed Rafi', film_or_album: 'Chaudhvin Ka Chand', year: '1960', youtube_id: 'n_X11G0VwzY' },
  { era: 'classical', language: 'hindi', song_title: 'Zindagi Ek Safar Hai Suhana', artist: 'Kishore Kumar', film_or_album: 'Andaz', year: '1971', youtube_id: 'K5y4QWk2_7k' },
  { era: 'classical', language: 'hindi', song_title: 'Roop Tera Mastana', artist: 'Kishore Kumar', film_or_album: 'Aradhana', year: '1969', youtube_id: 's28o9Z0G4d0' },
  { era: 'classical', language: 'hindi', song_title: 'Ek Ladki Ko Dekha Toh Aisa Laga', artist: 'Kumar Sanu', film_or_album: '1942: A Love Story', year: '1994', youtube_id: 'k6mG5qOQ85M' },
  { era: 'classical', language: 'hindi', song_title: 'Abhi Na Jao Chhod Kar', artist: 'Mohammed Rafi, Asha Bhosle', film_or_album: 'Hum Dono', year: '1961', youtube_id: 'bXvK7e-v3c0' },
  { era: 'classical', language: 'hindi', song_title: 'Tujhe Dekha Toh Yeh Jaana Sanam', artist: 'Kumar Sanu, Lata Mangeshkar', film_or_album: 'Dilwale Dulhania Le Jayenge', year: '1995', youtube_id: 'cNV5hLSa9ls' },
  { era: 'contemporary', language: 'hindi', song_title: 'Bande Mein Tha Dum Vande Mataram', artist: 'Sonu Nigam, Shreya Ghoshal', film_or_album: 'Lage Raho Munna Bhai', year: '2006', youtube_id: 'gD_V8_YyP8w' }
];

export const REGIONAL_SONGS: RiyazSong[] = [
  { era: 'contemporary', language: 'indian_other', indian_language: 'Tamil', song_title: 'Nenjukulle', artist: 'A.R. Rahman, Shakthisree Gopalan', film_or_album: 'Kadal', year: '2013', youtube_id: 'X_wHA57d38U' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Tamil', song_title: 'Rowdy Baby', artist: 'Dhanush, Dhee', film_or_album: 'Maari 2', year: '2018', youtube_id: 'xRn2gfzs9eg' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Telugu', song_title: 'Samajavaragamana', artist: 'Sid Sriram', film_or_album: 'Ala Vaikunthapurramuloo', year: '2019', youtube_id: 'ocTFAJu6t6E' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Malayalam', song_title: 'Malare', artist: 'Vijay Yesudas', film_or_album: 'Premam', year: '2015', youtube_id: 'yvTPL9f85y4' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Bengali', song_title: 'Amake Amar Moto Thakte Dao', artist: 'Anupam Roy', film_or_album: 'Autograph', year: '2010', youtube_id: 'q6Pq54O8d8c' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Tamil', song_title: 'Munbe Vaa', artist: 'Naresh Iyer, Shreya Ghoshal', film_or_album: 'Sillunu Oru Kaadhal', year: '2006', youtube_id: 'v_v4yRj7X-s' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Telugu', song_title: 'Naatu Naatu', artist: 'Rahul Sipligunj, Kaala Bhairava', film_or_album: 'RRR', year: '2022', youtube_id: 'sAzlWScHThc' },
  { era: 'classical', language: 'indian_other', indian_language: 'Tamil', song_title: 'Katrinile Varum Geetham', artist: 'M.S. Subbulakshmi', film_or_album: 'Meera', year: '1945', youtube_id: 'v6Z48A1vH4s' },
  { era: 'classical', language: 'indian_other', indian_language: 'Kannada', song_title: 'Bhagyada Lakshmi Baramma', artist: 'Bhimsen Joshi', film_or_album: 'Devotional', year: '1980', youtube_id: 't-A5P7e2x_w' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Malayalam', song_title: 'Kanoon', artist: 'K.S. Harisankar', film_or_album: 'Trance', year: '2020', youtube_id: 'yU8L_V8z7kU' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Punjabi', song_title: 'Pasoori', artist: 'Ali Sethi, Shae Gill', film_or_album: 'Coke Studio 14', year: '2022', youtube_id: '5Eqb_-j3FDA' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Marathi', song_title: 'Sairat Zaala Ji', artist: 'Ajay Gogavale, Chinmayi Sripada', film_or_album: 'Sairat', year: '2016', youtube_id: 'K4dC8Hk1Xws' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Bengali', song_title: 'Boba Tunnel', artist: 'Anupam Roy', film_or_album: 'Chotushkone', year: '2014', youtube_id: 'b-vO8k9g8u0' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Tamil', song_title: 'Kadhaippoma', artist: 'Sid Sriram', film_or_album: 'Oh My Kadavule', year: '2020', youtube_id: 'Y3R-F8C4x_w' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Telugu', song_title: 'Butta Bomma', artist: 'Armaan Malik', film_or_album: 'Ala Vaikunthapurramuloo', year: '2020', youtube_id: '2M4s8U4z8eU' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Tamil', song_title: 'Kannazhaga', artist: 'Dhanush, Shruti Haasan', film_or_album: '3', year: '2012', youtube_id: 'N-U4yRj7X_s' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Marathi', song_title: 'Aradhi Aradhi', artist: 'Ajay-Atul', film_or_album: 'Jait Re Jait', year: '1977', youtube_id: 'z-vO4k9w_sM' },
  { era: 'classical', language: 'indian_other', indian_language: 'Tamil', song_title: 'Chinnanchiru Kiliye', artist: 'Sudha Ragunathan', film_or_album: 'Bharathiyar Songs', year: '1998', youtube_id: 'v_vO4k9w8_w' },
  { era: 'classical', language: 'indian_other', indian_language: 'Bengali', song_title: 'Karar Ei Louho Kapat', artist: 'Kazi Nazrul Islam', film_or_album: 'Patriotic', year: '1922', youtube_id: 'N-U4yRj7X-w' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Punjabi', song_title: 'Ki Kehna', artist: 'Diljit Dosanjh', film_or_album: 'Roar', year: '2018', youtube_id: 'v-vO4k9w8sM' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Tamil', song_title: 'Vaseegara', artist: 'Bombay Jayashri', film_or_album: 'Minnale', year: '2001', youtube_id: 'bXvK7e-v3c0' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Malayalam', song_title: 'Ee Kaatru', artist: 'Karthik', film_or_album: 'Adam Joan', year: '2017', youtube_id: 'vUCM_O284wM' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Bengali', song_title: 'Rangabati', artist: 'Sona Mohapatra, Rituraj Mohanty', film_or_album: 'Coke Studio', year: '2015', youtube_id: 'vUCM_O284wL' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Gujarati', song_title: 'Radha Ne Shyam', artist: 'Sachin-Jigar', film_or_album: 'Garba Hits', year: '2019', youtube_id: 'vUCM_O284wK' },
  { era: 'classical', language: 'indian_other', indian_language: 'Telugu', song_title: 'Vatapi Ganapatim', artist: 'M. Balamuralikrishna', film_or_album: 'Classical Carnatic', year: '1975', youtube_id: 'vUCM_O284wJ' },
  { era: 'classical', language: 'indian_other', indian_language: 'Tamil', song_title: 'Jagadodharana', artist: 'Sudha Ragunathan', film_or_album: 'Purandara Dasa Devotional', year: '1995', youtube_id: 'vUCM_O284wI' },
  { era: 'classical', language: 'indian_other', indian_language: 'Sanskrit', song_title: 'Madhurashtakam', artist: 'M.S. Subbulakshmi', film_or_album: 'Stotrams', year: '1970', youtube_id: 'vUCM_O284wH' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Assamese', song_title: 'Bistirno Parore', artist: 'Bhupen Hazarika', film_or_album: 'Bistirno Parore', year: '1980', youtube_id: 'vUCM_O284wG' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Odia', song_title: 'Rangabati Original', artist: 'Jitendra Haripal, Krishna Patel', film_or_album: 'Folk', year: '1979', youtube_id: 'vUCM_O284wF' },
  { era: 'contemporary', language: 'indian_other', indian_language: 'Kannada', song_title: 'Sanju Weds Geetha Title', artist: 'Sonu Nigam', film_or_album: 'Sanju Weds Geetha', year: '2011', youtube_id: 'vUCM_O284wE' }
];

export const ENGLISH_SONGS: RiyazSong[] = [
  { era: 'contemporary', language: 'english', song_title: 'Fix You', artist: 'Coldplay', film_or_album: 'X&Y', year: '2005', youtube_id: 'k4V3_GkySI4' },
  { era: 'contemporary', language: 'english', song_title: 'Bohemian Rhapsody', artist: 'Queen', film_or_album: 'A Night at the Opera', year: '1975', youtube_id: 'fJ9rUzIMcZQ' },
  { era: 'contemporary', language: 'english', song_title: 'Imagine', artist: 'John Lennon', film_or_album: 'Imagine', year: '1971', youtube_id: 'YkgkThdzP-8' },
  { era: 'contemporary', language: 'english', song_title: 'Hotel California', artist: 'Eagles', film_or_album: 'Hotel California', year: '1976', youtube_id: '09839Y4u_c8' },
  { era: 'contemporary', language: 'english', song_title: 'Stairway to Heaven', artist: 'Led Zeppelin', film_or_album: 'Led Zeppelin IV', year: '1971', youtube_id: 'QkF3oxziUI4' },
  { era: 'contemporary', language: 'english', song_title: 'Someone Like You', artist: 'Adele', film_or_album: '21', year: '2011', youtube_id: 'hLQl3WQQoQ0' },
  { era: 'contemporary', language: 'english', song_title: 'Shape of You', artist: 'Ed Sheeran', film_or_album: 'Divide', year: '2017', youtube_id: 'JGwWNGJdvx8' },
  { era: 'classical', language: 'english', song_title: 'What a Wonderful World', artist: 'Louis Armstrong', film_or_album: 'Single', year: '1967', youtube_id: 'A3yCcXgbKrE' },
  { era: 'classical', language: 'english', song_title: 'Blowin in the Wind', artist: 'Bob Dylan', film_or_album: 'The Freewheelin Bob Dylan', year: '1963', youtube_id: 'vWwgpYB6l90' },
  { era: 'classical', language: 'english', song_title: 'Yesterday', artist: 'The Beatles', film_or_album: 'Help!', year: '1965', youtube_id: 'jo50505_c8' },
  { era: 'contemporary', language: 'english', song_title: 'Hey Jude', artist: 'The Beatles', film_or_album: 'Single', year: '1968', youtube_id: 'A139Y4u_c8' },
  { era: 'contemporary', language: 'english', song_title: 'Sound of Silence', artist: 'Simon & Garfunkel', film_or_album: 'Wednesday Morning, 3 A.M.', year: '1964', youtube_id: 'fJ9rUzIMcZM' },
  { era: 'contemporary', language: 'english', song_title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', film_or_album: 'Bridge Over Troubled Water', year: '1970', youtube_id: 'fJ9rUzIMcZL' },
  { era: 'contemporary', language: 'english', song_title: 'Sweet Child O Mine', artist: 'Guns N Roses', film_or_album: 'Appetite for Destruction', year: '1987', youtube_id: 'fJ9rUzIMcZK' },
  { era: 'contemporary', language: 'english', song_title: 'Comfortably Numb', artist: 'Pink Floyd', film_or_album: 'The Wall', year: '1979', youtube_id: 'fJ9rUzIMcZJ' },
  { era: 'contemporary', language: 'english', song_title: 'Wish You Were Here', artist: 'Pink Floyd', film_or_album: 'Wish You Were Here', year: '1975', youtube_id: 'fJ9rUzIMcZI' },
  { era: 'contemporary', language: 'english', song_title: 'Hallelujah', artist: 'Jeff Buckley', film_or_album: 'Grace', year: '1994', youtube_id: 'fJ9rUzIMcZH' },
  { era: 'contemporary', language: 'english', song_title: 'Dancing Queen', artist: 'ABBA', film_or_album: 'Arrival', year: '1976', youtube_id: 'fJ9rUzIMcZG' },
  { era: 'contemporary', language: 'english', song_title: 'Billie Jean', artist: 'Michael Jackson', film_or_album: 'Thriller', year: '1982', youtube_id: 'fJ9rUzIMcZF' },
  { era: 'contemporary', language: 'english', song_title: 'Stayin Alive', artist: 'Bee Gees', film_or_album: 'Saturday Night Fever', year: '1977', youtube_id: 'fJ9rUzIMcZE' },
  { era: 'contemporary', language: 'english', song_title: 'Superstition', artist: 'Stevie Wonder', film_or_album: 'Talking Book', year: '1972', youtube_id: 'fJ9rUzIMcZD' },
  { era: 'contemporary', language: 'english', song_title: 'Respect', artist: 'Aretha Franklin', film_or_album: 'I Never Loved a Man the Way I Love You', year: '1967', youtube_id: 'fJ9rUzIMcZC' },
  { era: 'contemporary', language: 'english', song_title: 'A Change Is Gonna Come', artist: 'Sam Cooke', film_or_album: 'Single', year: '1964', youtube_id: 'fJ9rUzIMcZB' },
  { era: 'contemporary', language: 'english', song_title: 'Purple Haze', artist: 'Jimi Hendrix', film_or_album: 'Are You Experienced', year: '1967', youtube_id: 'fJ9rUzIMcZA' },
  { era: 'classical', language: 'english', song_title: 'Smells Like Teen Spirit', artist: 'Nirvana', film_or_album: 'Nevermind', year: '1991', youtube_id: 'fJ9rUzIMcZ9' },
  { era: 'classical', language: 'english', song_title: 'Losing My Religion', artist: 'R.E.M.', film_or_album: 'Out of Time', year: '1991', youtube_id: 'fJ9rUzIMcZ8' },
  { era: 'classical', language: 'english', song_title: 'Creep', artist: 'Radiohead', film_or_album: 'Pablo Honey', year: '1992', youtube_id: 'fJ9rUzIMcZ7' },
  { era: 'classical', language: 'english', song_title: 'One', artist: 'U2', film_or_album: 'Achtung Baby', year: '1991', youtube_id: 'fJ9rUzIMcZ6' },
  { era: 'contemporary', language: 'english', song_title: 'Rolling in the Deep', artist: 'Adele', film_or_album: '21', year: '2011', youtube_id: 'fJ9rUzIMcZ5' },
  { era: 'contemporary', language: 'english', song_title: 'Bad Guy', artist: 'Billie Eilish', film_or_album: 'When We All Fall Asleep', year: '2019', youtube_id: 'fJ9rUzIMcZ4' }
];

export const WORLD_SONGS: RiyazSong[] = [
  { era: 'contemporary', language: 'world', world_language: 'Spanish', song_title: 'La Bamba', artist: 'Los Lobos', film_or_album: 'La Bamba', year: '1987', youtube_id: 'nLAWPrPAZWY' },
  { era: 'contemporary', language: 'world', world_language: 'Italian', song_title: 'Bella Ciao', artist: 'Manu Chao', film_or_album: 'Folk Standard', year: '2000', youtube_id: '4gO7Ye-L_2s' },
  { era: 'contemporary', language: 'world', world_language: 'French', song_title: 'Ne me quitte pas', artist: 'Jacques Brel', film_or_album: 'Single', year: '1959', youtube_id: 'ocTFAJu6t6F' },
  { era: 'contemporary', language: 'world', world_language: 'Portuguese', song_title: 'Garota de Ipanema', artist: 'Stan Getz, Joao Gilberto', film_or_album: 'Getz/Gilberto', year: '1964', youtube_id: 'yvTPL9f85y5' },
  { era: 'contemporary', language: 'world', world_language: 'Japanese', song_title: 'Sukiyaki', artist: 'Kyu Sakamoto', film_or_album: 'Single', year: '1961', youtube_id: 'q6Pq54O8d8d' },
  { era: 'contemporary', language: 'world', world_language: 'French', song_title: 'La Vie en Rose', artist: 'Edith Piaf', film_or_album: 'Single', year: '1947', youtube_id: 'v_v4yRj7X-t' },
  { era: 'contemporary', language: 'world', world_language: 'Spanish', song_title: 'Despacito', artist: 'Luis Fonsi, Daddy Yankee', film_or_album: 'Vida', year: '2017', youtube_id: 'kJQP7kiw5Fk' },
  { era: 'classical', language: 'world', world_language: 'German', song_title: 'Ode to Joy (Symphony No. 9)', artist: 'Ludwig van Beethoven', film_or_album: 'Classical Masterpiece', year: '1824', youtube_id: 't-A5P7e2x_x' },
  { era: 'classical', language: 'world', world_language: 'Italian', song_title: 'Nessun Dorma', artist: 'Luciano Pavarotti', film_or_album: 'Turandot (Puccini)', year: '1972', youtube_id: 'yU8L_V8z7kV' },
  { era: 'contemporary', language: 'world', world_language: 'Arabic', song_title: 'Enta Omri', artist: 'Umm Kulthum', film_or_album: 'Enta Omri', year: '1964', youtube_id: 'yU8L_V8z7kW' },
  { era: 'contemporary', language: 'world', world_language: 'Spanish', song_title: 'Quizas, Quizas, Quizas', artist: 'Nat King Cole', film_or_album: 'The Very Best of', year: '1958', youtube_id: 'v_vO4k9w8_v' },
  { era: 'contemporary', language: 'world', world_language: 'French', song_title: 'Non, je ne regrette rien', artist: 'Edith Piaf', film_or_album: 'Single', year: '1960', youtube_id: 'N-U4yRj7X-v' },
  { era: 'contemporary', language: 'world', world_language: 'Cape Verdean', song_title: 'Sodade', artist: 'Cesaria Evora', film_or_album: 'Miss Perfumado', year: '1992', youtube_id: 'v-vO4k9w8sN' },
  { era: 'contemporary', language: 'world', world_language: 'Farsi', song_title: 'Bahar-e Delneshin', artist: 'Gholam-Hossein Banan', film_or_album: 'Classical Persian', year: '1950', youtube_id: 'bXvK7e-v3d0' },
  { era: 'contemporary', language: 'world', world_language: 'Zulu', song_title: 'Shosholoza', artist: 'Ladysmith Black Mambazo', film_or_album: 'Shosholoza', year: '1994', youtube_id: 'vUCM_O284wN' },
  { era: 'contemporary', language: 'world', world_language: 'Korean', song_title: 'Gangnam Style', artist: 'PSY', film_or_album: 'Psy 6th (Six Rules)', year: '2012', youtube_id: '9bZkp7q19f0' },
  { era: 'contemporary', language: 'world', world_language: 'Mali French', song_title: 'Je Pense a Toi', artist: 'Amadou & Mariam', film_or_album: 'Sou ni tile', year: '1998', youtube_id: '9bZkp7q19f1' },
  { era: 'classical', language: 'world', world_language: 'Italian', song_title: 'Con te partirò', artist: 'Andrea Bocelli', film_or_album: 'Bocelli', year: '1995', youtube_id: '9bZkp7q19f2' },
  { era: 'classical', language: 'world', world_language: 'Spanish', song_title: 'Chan Chan', artist: 'Buena Vista Social Club', film_or_album: 'Buena Vista Social Club', year: '1997', youtube_id: '9bZkp7q19f3' },
  { era: 'contemporary', language: 'world', world_language: 'French', song_title: 'Quelqu un m a dit', artist: 'Carla Bruni', film_or_album: 'Quelqu un m a dit', year: '2002', youtube_id: '9bZkp7q19f4' },
  { era: 'contemporary', language: 'world', world_language: 'Spanish', song_title: 'Amor de Mis Amores', artist: 'Natalia Lafourcade', film_or_album: 'Musas', year: '2017', youtube_id: '9bZkp7q19f5' },
  { era: 'contemporary', language: 'world', world_language: 'Italian', song_title: 'Caruso', artist: 'Lucio Dalla', film_or_album: 'DallAmeriCaruso', year: '1986', youtube_id: '9bZkp7q19f6' },
  { era: 'contemporary', language: 'world', world_language: 'Spanish', song_title: 'Guantanamera', artist: 'Celia Cruz', film_or_album: 'Single', year: '1966', youtube_id: '9bZkp7q19f7' },
  { era: 'contemporary', language: 'world', world_language: 'Turkish', song_title: 'Şımarık', artist: 'Tarkan', film_or_album: 'Karma', year: '1997', youtube_id: '9bZkp7q19f8' },
  { era: 'classical', language: 'world', world_language: 'French', song_title: 'Je te veux', artist: 'Erik Satie', film_or_album: 'Valse pour piano', year: '1903', youtube_id: '9bZkp7q19f9' },
  { era: 'classical', language: 'world', world_language: 'Spanish', song_title: 'Malagueña Salerosa', artist: 'Chingon', film_or_album: 'Kill Bill Vol. 2', year: '2004', youtube_id: '9bZkp7q19fa' },
  { era: 'classical', language: 'world', world_language: 'Farsi', song_title: 'Gole Yakh', artist: 'Kourosh Yaghmaei', film_or_album: 'Gole Yakh', year: '1973', youtube_id: '9bZkp7q19fb' },
  { era: 'contemporary', language: 'world', world_language: 'Italian', song_title: 'L Italiano', artist: 'Toto Cutugno', film_or_album: 'L Italiano', year: '1983', youtube_id: '9bZkp7q19fc' },
  { era: 'contemporary', language: 'world', world_language: 'Greek', song_title: 'Misirlou', artist: 'Dick Dale', film_or_album: 'Pulp Fiction', year: '1962', youtube_id: '9bZkp7q19fd' },
  { era: 'contemporary', language: 'world', world_language: 'Hebrew', song_title: 'Hava Nagila', artist: 'Harry Belafonte', film_or_album: 'Single', year: '1959', youtube_id: '9bZkp7q19fe' }
];
